(defstruct wkey id)
(defun many-aggregate-keys (n)
  (let ((h (make-hash-table :test 'eq)) (v (make-hash-table :test 'equal))
        (conses nil) (vectors nil) (structs nil))
    (dotimes (i n)
      (push (cons i i) conses)
      (push (vector i) vectors)
      (push (make-wkey :id i) structs))
    (dolist (k conses) (setf (gethash k h) 1))
    (dolist (k vectors) (setf (gethash k h) 2) (setf (gethash k v) 4))
    (dolist (k structs) (setf (gethash k h) 3))
    (dolist (k conses) (setf (car k) :moved))
    (let ((sum 0) (misses 0) (i 0))
      (dolist (k conses) (incf sum (gethash k h 0)))
      (dolist (k vectors) (incf sum (gethash k h 0)) (incf sum (gethash k v 0)))
      (dolist (k structs) (incf sum (gethash k h 0)))
      (dotimes (j 10)
        (unless (gethash (cons :moved j) h) (incf misses))
        (unless (gethash (vector j) h) (incf misses))
        (unless (gethash (vector j) v) (incf misses))
        (unless (gethash (make-wkey :id j) h) (incf misses)))
      (dolist (k conses) (when (evenp i) (remhash k h)) (incf i))
      (list (hash-table-count h) (hash-table-count v) sum misses))))
(let ((t0 (get-internal-real-time)))
  (print (many-aggregate-keys 100000))
  (format t "~%ms=~D~%" (round (* 1000 (- (get-internal-real-time) t0)) internal-time-units-per-second)))
