(ql:quickload '("mito" "dbd-postgres"))
(setf mito:*mito-migration-logger-stream* nil)
(mito:deftable spec ()
  ((title :col-type (:varchar 64))
   (body :col-type (or :text :null)))
  (:table-name "mito_spec"))
(mito:deftable article ()
  ((title :col-type (:varchar 64))
   (body :col-type (or :text :null)))
  (:table-name "mito_article_jvm"))
(mito:connect-toplevel :postgres :database-name "postgres" :username "postgres"
                       :password "mito" :host "127.0.0.1" :port 5432)
(dolist (statement (mito:table-definition 'spec))
  (format t "~a~%" (sxql:yield statement)))
(mito:execute-sql "DROP TABLE IF EXISTS mito_article_jvm")
(mito:ensure-table-exists 'article)
(let ((a (mito:create-dao 'article :title "alpha" :body "first")))
  (format t "created ~a ~a~%" (mito:object-id a) (slot-value a 'title)))
(mito:insert-dao (make-instance 'article :title "beta" :body nil))
(let ((found (mito:find-dao 'article :title "alpha")))
  (format t "found ~a ~a~%" (mito:object-id found) (slot-value found 'body))
  (setf (slot-value found 'body) "edited")
  (mito:save-dao found))
(format t "after-save ~a~%" (slot-value (mito:find-dao 'article :title "alpha") 'body))
(format t "selected ~a~%"
        (mapcar (lambda (o) (slot-value o 'title))
                (mito:select-dao 'article
                                 (sxql:where (:like :title "%a"))
                                 (sxql:order-by :id))))
(mito:delete-dao (mito:find-dao 'article :title "beta"))
(format t "remaining ~a~%" (length (mito:select-dao 'article)))
(mito:disconnect-toplevel)
