(defun handler (env)
  (declare (ignore env))
  (let ((octets (make-array 3 :element-type '(unsigned-byte 8))))
    (setf (aref octets 0) #xff)
    (setf (aref octets 1) #xfe)
    (setf (aref octets 2) #x41)
    (list 200 (list :content-type "application/octet-stream") octets)))

(defvar *server* (rontolisp::%http-server-start #'handler 0 nil))
(rontolisp::%http-server-stop *server*)
