package root:component;

world root {
  import wasi:cli/types@0.3.0;
  import wasi:cli/stdout@0.3.0;
  import wasi:cli/stdin@0.3.0;
  import wasi:cli/environment@0.3.0;
  import wasi:clocks/types@0.3.0;
  import wasi:clocks/system-clock@0.3.0;
  import wasi:clocks/monotonic-clock@0.3.0;
  import wasi:filesystem/types@0.3.0;
  import wasi:filesystem/preopens@0.3.0;
  import wasi:random/random@0.3.0;
  import wasi:sockets/types@0.3.0;
  import wasi:cli/stderr@0.3.0;

  export wasi:cli/run@0.3.0;
}
package wasi:cli@0.3.0 {
  interface types {
    enum error-code {
      io,
      illegal-byte-sequence,
      pipe,
    }
  }
  interface stdout {
    use types.{error-code};

    write-via-stream: func(data: stream<u8>) -> future<result<_, error-code>>;
  }
  interface stdin {
    use types.{error-code};

    read-via-stream: func() -> tuple<stream<u8>, future<result<_, error-code>>>;
  }
  interface environment {
    get-environment: func() -> list<tuple<string, string>>;
  }
  interface stderr {
    use types.{error-code};

    write-via-stream: func(data: stream<u8>) -> future<result<_, error-code>>;
  }
  interface run {
    run: async func() -> result;
  }
}


package wasi:clocks@0.3.0 {
  interface types {
    type duration = u64;
  }
  interface system-clock {
    record instant {
      seconds: s64,
      nanoseconds: u32,
    }

    now: func() -> instant;
  }
  interface monotonic-clock {
    use types.{duration};

    type mark = u64;

    now: func() -> mark;

    wait-for: async func(how-long: duration);
  }
}


package wasi:filesystem@0.3.0 {
  interface types {
    resource descriptor {
      read-via-stream: func(offset: filesize) -> tuple<stream<u8>, future<result<_, error-code>>>;
      append-via-stream: func(data: stream<u8>) -> future<result<_, error-code>>;
      open-at: async func(path-flags: path-flags, path: string, open-flags: open-flags, %flags: descriptor-flags) -> result<descriptor, error-code>;
    }

    type filesize = u64;

    variant error-code {
      access,
      already,
      bad-descriptor,
      busy,
      deadlock,
      quota,
      exist,
      file-too-large,
      illegal-byte-sequence,
      in-progress,
      interrupted,
      invalid,
      io,
      is-directory,
      loop,
      too-many-links,
      message-size,
      name-too-long,
      no-device,
      no-entry,
      no-lock,
      insufficient-memory,
      insufficient-space,
      not-directory,
      not-empty,
      not-recoverable,
      unsupported,
      no-tty,
      no-such-device,
      overflow,
      not-permitted,
      pipe,
      read-only,
      invalid-seek,
      text-file-busy,
      cross-device,
      other(option<string>),
    }

    flags path-flags {
      symlink-follow,
    }

    flags open-flags {
      create,
      directory,
      exclusive,
      truncate,
    }

    flags descriptor-flags {
      read,
      write,
      file-integrity-sync,
      data-integrity-sync,
      requested-write-sync,
      mutate-directory,
    }
  }
  interface preopens {
    use types.{descriptor};

    get-directories: func() -> list<tuple<descriptor, string>>;
  }
}


package wasi:random@0.3.0 {
  interface random {
    get-random-u64: func() -> u64;
  }
}


package wasi:sockets@0.3.0 {
  interface types {
    resource tcp-socket {
      create: static func(address-family: ip-address-family) -> result<tcp-socket, error-code>;
      bind: func(local-address: ip-socket-address) -> result<_, error-code>;
      connect: async func(remote-address: ip-socket-address) -> result<_, error-code>;
      listen: func() -> result<stream<tcp-socket>, error-code>;
      send: func(data: stream<u8>) -> future<result<_, error-code>>;
      receive: func() -> tuple<stream<u8>, future<result<_, error-code>>>;
      get-local-address: func() -> result<ip-socket-address, error-code>;
    }

    enum ip-address-family {
      ipv4,
      ipv6,
    }

    variant error-code {
      access-denied,
      not-supported,
      invalid-argument,
      out-of-memory,
      timeout,
      invalid-state,
      address-not-bindable,
      address-in-use,
      remote-unreachable,
      connection-refused,
      connection-broken,
      connection-reset,
      connection-aborted,
      datagram-too-large,
      other(option<string>),
    }

    type ipv4-address = tuple<u8, u8, u8, u8>;

    record ipv4-socket-address {
      port: u16,
      address: ipv4-address,
    }

    type ipv6-address = tuple<u16, u16, u16, u16, u16, u16, u16, u16>;

    record ipv6-socket-address {
      port: u16,
      flow-info: u32,
      address: ipv6-address,
      scope-id: u32,
    }

    variant ip-socket-address {
      ipv4(ipv4-socket-address),
      ipv6(ipv6-socket-address),
    }
  }
}
