(defun bench (label thunk reps)
  (dotimes (i 3) (funcall thunk))
  (let ((t0 (get-internal-real-time)))
    (dotimes (i reps) (funcall thunk))
    (format t "~a ~,3f ms/call~%" label
            (/ (* 1000.0 (- (get-internal-real-time) t0))
               (* reps internal-time-units-per-second)))))

(dolist (n '(256 512))
  (let ((ad (linalg:ones (list n n)))
        (bd (linalg:ones (list n n)))
        (af (linalg:ones (list n n) :element-type 'single-float))
        (bf (linalg:ones (list n n) :element-type 'single-float)))
    (bench (format nil "matmul n=~d f64" n) (lambda () (linalg:matmul ad bd)) 20)
    (bench (format nil "matmul n=~d f32" n) (lambda () (linalg:matmul af bf)) 20)))

(let* ((n 400000)
       (ad (linalg:ones (list n)))
       (af (linalg:ones (list n) :element-type 'single-float)))
  (bench "add   1d f64" (lambda () (linalg:add ad ad)) 50)
  (bench "add   1d f32" (lambda () (linalg:add af af)) 50)
  (bench "dot   1d f64" (lambda () (linalg:dot ad ad)) 50)
  (bench "dot   1d f32" (lambda () (linalg:dot af af)) 50)
  (bench "exp   1d f64" (lambda () (linalg:exp ad)) 50)
  (bench "exp   1d f32" (lambda () (linalg:exp af)) 50)
  (bench "sum   1d f64" (lambda () (linalg:sum ad)) 50)
  (bench "sum   1d f32" (lambda () (linalg:sum af)) 50))
