(defun build (n)
  (let ((a (make-array n :element-type 'double-float)))
    (dotimes (i n) (setf (aref a i) (coerce (1+ i) 'double-float)))
    a))
(defun run (a n)
  (let ((s 0.0d0))
    (dotimes (i n) (setq s (+ s (aref a (random 1000000)))))
    s))
(print (run (build 1000000) 10000000))
