(defun build (n)
  (let ((a (make-array n :element-type '(unsigned-byte 32))))
    (dotimes (i n) (setf (aref a i) (1+ i)))
    a))
(defun run (a n)
  (let ((s 0))
    (dotimes (i n) (setq s (+ s (aref a (random 1000000)))))
    s))
(print (run (build 1000000) 10000000))
