(defun build (n)
  (let ((a (make-array n)))
    (dotimes (i n) (setf (aref a i) (1+ i)))
    a))
(defun run (a n)
  (let ((s 0))
    (dotimes (i n) (setq s (+ s (aref a (random 10000)))))
    s))
(print (run (build 10000) 10000000))
