package am.ik.rontolisp.e2e;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;

import am.ik.rontolisp.cli.RontoLispCli;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * The other half of {@code -o out.jar}: that the jar a rontolisp build writes really is
 * an ordinary Maven artifact — installed with no coordinate flags at all, then depended
 * on from a plain Maven project that compiles Java against the typed exports and runs
 * them.
 * <p>
 * Opt-in ({@code -Drontolisp.jar.e2e=true}), because it shells out to Maven and INSTALLS
 * into the developer's real local repository — which it must, since that is exactly what
 * {@code install-file} does and what a consumer's build then reads. The coordinates are
 * namespaced to this test and the directory is removed again afterwards.
 *
 * <pre>
 * ./mvnw -Dtest=JarMavenConsumerE2eTest -DfailIfNoTests=false -Drontolisp.jar.e2e=true test
 * </pre>
 */
class JarMavenConsumerE2eTest {

	private static final String GROUP_ID = "am.ik.rontolisp.jare2e";

	private static final String ARTIFACT_ID = "kernels";

	private static final String VERSION = "0.0.1-E2E";

	@TempDir
	Path tempDir;

	@Test
	void anInstalledJarIsAnOrdinaryDependencyOfAPlainMavenProject() throws Exception {
		assumeTrue("true".equals(System.getProperty("rontolisp.jar.e2e")),
				"the jar consumer E2E is opt-in (it installs into the real local repository):"
						+ " pass -Drontolisp.jar.e2e=true");
		Path maven = maven();
		assumeTrue(maven != null, "no Maven executable found (mvn on PATH, MAVEN_HOME, or the ./mvnw distribution)");
		Path localRepository = Path.of(System.getProperty("user.home"), ".m2", "repository");
		String installPlugin = installFileGoal(localRepository);
		assumeTrue(installPlugin != null,
				"maven-install-plugin is not in the local repository, and this test runs Maven offline");
		Path installed = localRepository.resolve(GROUP_ID.replace('.', '/'));

		Path jar = compileLibraryJar();
		try {
			// The point of the embedded META-INF/maven pair: no -DgroupId, no
			// -DartifactId, no -Dversion, no -DpomFile. The coordinates are IN the jar.
			run(maven, this.tempDir, "-o", "-q", installPlugin, "-Dfile=" + jar);
			Path artifactDirectory = installed.resolve(ARTIFACT_ID).resolve(VERSION);
			assertThat(artifactDirectory.resolve(ARTIFACT_ID + "-" + VERSION + ".jar")).exists();
			// And the pom Maven writes beside it is the one the jar carried, not a stub
			// synthesized from flags.
			assertThat(Files.readString(artifactDirectory.resolve(ARTIFACT_ID + "-" + VERSION + ".pom")))
				.contains("Generated by rontolisp")
				.contains("<dependencies/>");

			Path consumer = writeConsumerProject();
			run(maven, consumer, "-o", "-q", "compile");
			String output = run(javaExecutable(), consumer, "-cp", consumer.resolve("target/classes")
					+ java.io.File.pathSeparator + artifactDirectory.resolve(ARTIFACT_ID + "-" + VERSION + ".jar"),
					"app.App");
			// scaledSum reads a defvar the class initializer set, and norm2 crosses the
			// packed-array handle -- whose class the consumer never declared a dependency
			// on, because it travelled inside the jar.
			assertThat(output.lines().toList()).containsExactly("12.0", "5.0");
		}
		finally {
			deleteRecursively(installed);
		}
	}

	/** Compiles the library to a jar exactly as the command line would. */
	private Path compileLibraryJar() throws Exception {
		Path source = this.tempDir.resolve("kernels.lisp");
		Files.writeString(source, """
				(defvar *scale* 2.0)
				(defun scaled-sum (a b) (* *scale* (+ a b)))
				(defun norm2 (x) (sqrt (vec:dot x x)))
				(rontolisp:jvm-export 'scaled-sum :params '(:float :float) :returns :float)
				(rontolisp:jvm-export 'norm2 :params '(:float-vector) :returns :float)
				""");
		Path jar = this.tempDir.resolve(ARTIFACT_ID + "-" + VERSION + ".jar");
		RontoLispCli cli = new RontoLispCli(new ByteArrayInputStream(new byte[0]),
				new PrintStream(new ByteArrayOutputStream()));
		cli.run(new String[] { source.toString(), "-o", jar.toString(), "--class-name", "com.example.Kernels",
				"--maven-coordinates", GROUP_ID + ":" + ARTIFACT_ID + ":" + VERSION, "--no-main" });
		assertThat(jar).exists();
		return jar;
	}

	private Path writeConsumerProject() throws Exception {
		Path consumer = this.tempDir.resolve("consumer");
		Path app = consumer.resolve("src/main/java/app");
		Files.createDirectories(app);
		Files.writeString(consumer.resolve("pom.xml"), """
				<project xmlns="http://maven.apache.org/POM/4.0.0">
				  <modelVersion>4.0.0</modelVersion>
				  <groupId>app</groupId>
				  <artifactId>consumer</artifactId>
				  <version>1.0.0</version>
				  <properties>
				    <maven.compiler.release>%d</maven.compiler.release>
				    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
				  </properties>
				  <dependencies>
				    <dependency>
				      <groupId>%s</groupId>
				      <artifactId>%s</artifactId>
				      <version>%s</version>
				    </dependency>
				  </dependencies>
				</project>
				""".formatted(Runtime.version().feature(), GROUP_ID, ARTIFACT_ID, VERSION));
		Files.writeString(app.resolve("App.java"), """
				package app;

				import am.ik.rontolisp.runtime.RontoFloatArray;
				import com.example.Kernels;

				public class App {
					public static void main(String[] args) {
						System.out.println(Kernels.scaledSum(2.5, 3.5));
						System.out.println(Kernels.norm2(RontoFloatArray.of(new double[] { 3.0, 4.0 })));
					}
				}
				""");
		return consumer;
	}

	/**
	 * The fully qualified {@code install-file} goal at the newest version the local
	 * repository holds. The {@code install:} prefix would resolve the version out of the
	 * plugin's remote metadata, which offline Maven cannot read.
	 */
	private static @Nullable String installFileGoal(Path localRepository) throws Exception {
		Path plugin = localRepository.resolve("org/apache/maven/plugins/maven-install-plugin");
		if (!Files.isDirectory(plugin)) {
			return null;
		}
		try (Stream<Path> versions = Files.list(plugin)) {
			return versions.filter(Files::isDirectory)
				.map(path -> path.getFileName().toString())
				.filter(version -> Files
					.isRegularFile(plugin.resolve(version).resolve("maven-install-plugin-" + version + ".jar")))
				.max(Comparator.naturalOrder())
				.map(version -> "org.apache.maven.plugins:maven-install-plugin:" + version + ":install-file")
				.orElse(null);
		}
	}

	private static @Nullable Path maven() {
		List<Path> candidates = new ArrayList<>();
		String path = System.getenv("PATH");
		if (path != null) {
			for (String directory : path.split(java.io.File.pathSeparator)) {
				candidates.add(Path.of(directory, "mvn"));
			}
		}
		String home = System.getenv("MAVEN_HOME");
		if (home != null) {
			candidates.add(Path.of(home, "bin", "mvn"));
		}
		// The ./mvnw wrapper's own downloaded distribution, which is what a machine that
		// only ever builds through the wrapper has.
		Path wrapper = Path.of(System.getProperty("user.home"), ".m2", "wrapper", "dists");
		if (Files.isDirectory(wrapper)) {
			try (Stream<Path> tree = Files.walk(wrapper, 4)) {
				tree.filter(candidate -> candidate.endsWith(Path.of("bin", "mvn"))).forEach(candidates::add);
			}
			catch (Exception ignored) {
				// Fall through to whatever the other candidates found.
			}
		}
		return candidates.stream().filter(Files::isExecutable).findFirst().orElse(null);
	}

	private static Path javaExecutable() {
		return Path.of(System.getProperty("java.home"), "bin", "java");
	}

	private static String run(Path executable, Path directory, String... arguments) throws Exception {
		List<String> command = new ArrayList<>();
		command.add(executable.toString());
		command.addAll(List.of(arguments));
		Process process = new ProcessBuilder(command).directory(directory.toFile()).redirectErrorStream(true).start();
		String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
		int status = process.waitFor();
		assertThat(status).describedAs("%s exited %d:%n%s", command, status, output).isZero();
		return output;
	}

	private static void deleteRecursively(Path root) throws Exception {
		if (!Files.exists(root)) {
			return;
		}
		try (Stream<Path> tree = Files.walk(root)) {
			for (Path path : tree.sorted(Comparator.reverseOrder()).toList()) {
				Files.deleteIfExists(path);
			}
		}
	}

}
