package am.ik.rontolisp.e2e;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.stream.Stream;

import am.ik.rontolisp.cli.RontoLispCli;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * The other half of {@code -o out.jar}: that the jar a rontolisp build writes really is
 * an ordinary Maven artifact — installed with no coordinate flags at all, then depended
 * on from a plain Maven project that compiles Java against the typed exports and runs
 * them.
 * <p>
 * Opt-in ({@code -Drontolisp.jar.e2e=true}), because it shells out to Maven and INSTALLS
 * into the local repository of the build running it — which it must, since that is
 * exactly what {@code install-file} does and what a consumer's build then reads. The
 * coordinates are namespaced to this test and the directory is removed again afterwards.
 * <p>
 * Every shelled-out build runs on the Maven running this test and that local repository
 * (the root pom's surefire configuration passes both), with the resources, compiler and
 * install plugins at the versions the root pom pins — never an {@code mvn} found on PATH,
 * whose default bindings move with the machine's Maven. The offline builds therefore
 * resolve only what the seeding {@code install} executed in full.
 *
 * <pre>
 * ./mvnw install -DskipTests
 * ./mvnw -Dtest=JarMavenConsumerE2eTest -DfailIfNoTests=false -Drontolisp.jar.e2e=true test
 * </pre>
 */
class JarMavenConsumerE2eTest {

	private static final String GROUP_ID = "am.ik.rontolisp.jare2e";

	private static final String ARTIFACT_ID = "kernels";

	private static final String VERSION = "0.0.1-E2E";

	@TempDir
	Path tempDir;

	@Test
	void anInstalledJarIsAnOrdinaryDependencyOfAPlainMavenProject() throws Exception {
		Ready ready = assumeReady();
		Path localRepository = ready.localRepository();
		Path installed = localRepository.resolve(GROUP_ID.replace('.', '/'));

		Path jar = compileLibraryJar();
		try {
			// The point of the embedded META-INF/maven pair: no -DgroupId, no
			// -DartifactId, no -Dversion, no -DpomFile. The coordinates are IN the jar.
			run(this.tempDir, ready.maven("-o", "-q", ready.installFileGoal(), "-Dfile=" + jar));
			Path artifactDirectory = installed.resolve(ARTIFACT_ID).resolve(VERSION);
			assertThat(artifactDirectory.resolve(ARTIFACT_ID + "-" + VERSION + ".jar")).exists();
			// And the pom Maven writes beside it is the one the jar carried, not a stub
			// synthesized from flags.
			assertThat(Files.readString(artifactDirectory.resolve(ARTIFACT_ID + "-" + VERSION + ".pom")))
				.contains("Generated by rontolisp")
				.contains("<dependencies/>");

			Path consumer = writeConsumerProject(ready);
			run(consumer, ready.maven("-o", "-q", "compile"));
			String output = run(consumer,
					List.of(javaExecutable().toString(), "-cp",
							consumer.resolve("target/classes") + java.io.File.pathSeparator
									+ artifactDirectory.resolve(ARTIFACT_ID + "-" + VERSION + ".jar"),
							"app.App"));
			// scaledSum reads a defvar the class initializer set, and norm2 crosses the
			// packed-array handle -- whose class the consumer never declared a dependency
			// on, because it travelled inside the jar.
			assertThat(output.lines().toList()).containsExactly("12.0", "5.0");
		}
		finally {
			deleteRecursively(installed);
		}
	}

	/** Compiles the library to a jar exactly as the command line would. */
	private Path compileLibraryJar() throws Exception {
		Path source = this.tempDir.resolve("kernels.lisp");
		Files.writeString(source, """
				(defvar *scale* 2.0)
				(defun scaled-sum (a b) (* *scale* (+ a b)))
				(defun norm2 (x) (sqrt (vec:dot x x)))
				(rontolisp:jvm-export 'scaled-sum :params '(:float :float) :returns :float)
				(rontolisp:jvm-export 'norm2 :params '(:float-vector) :returns :float)
				""");
		Path jar = this.tempDir.resolve(ARTIFACT_ID + "-" + VERSION + ".jar");
		RontoLispCli cli = new RontoLispCli(new ByteArrayInputStream(new byte[0]),
				new PrintStream(new ByteArrayOutputStream()));
		cli.run(new String[] { source.toString(), "-o", jar.toString(), "--class-name", "com.example.Kernels",
				"--maven-coordinates", GROUP_ID + ":" + ARTIFACT_ID + ":" + VERSION, "--no-main" });
		assertThat(jar).exists();
		return jar;
	}

	private Path writeConsumerProject(Ready ready) throws Exception {
		Path consumer = this.tempDir.resolve("consumer");
		Path app = consumer.resolve("src/main/java/app");
		Files.createDirectories(app);
		Files.writeString(consumer.resolve("pom.xml"), """
				<project xmlns="http://maven.apache.org/POM/4.0.0">
				  <modelVersion>4.0.0</modelVersion>
				  <groupId>app</groupId>
				  <artifactId>consumer</artifactId>
				  <version>1.0.0</version>
				  <properties>
				    <maven.compiler.release>%d</maven.compiler.release>
				    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
				  </properties>
				  <dependencies>
				    <dependency>
				      <groupId>%s</groupId>
				      <artifactId>%s</artifactId>
				      <version>%s</version>
				    </dependency>
				  </dependencies>
				  <build>
				    <plugins>
				      <plugin>
				        <groupId>org.apache.maven.plugins</groupId>
				        <artifactId>maven-resources-plugin</artifactId>
				        <version>%s</version>
				      </plugin>
				      <plugin>
				        <groupId>org.apache.maven.plugins</groupId>
				        <artifactId>maven-compiler-plugin</artifactId>
				        <version>%s</version>
				      </plugin>
				    </plugins>
				  </build>
				</project>
				""".formatted(Runtime.version().feature(), GROUP_ID, ARTIFACT_ID, VERSION, ready.resourcesPlugin(),
				ready.compilerPlugin()));
		Files.writeString(app.resolve("App.java"), """
				package app;

				import am.ik.rontolisp.runtime.RontoFloatArray;
				import com.example.Kernels;

				public class App {
					public static void main(String[] args) {
						System.out.println(Kernels.scaledSum(2.5, 3.5));
						System.out.println(Kernels.norm2(RontoFloatArray.of(new double[] { 3.0, 4.0 })));
					}
				}
				""");
		return consumer;
	}

	private static Ready assumeReady() {
		assumeTrue("true".equals(System.getProperty("rontolisp.jar.e2e")),
				"the jar consumer E2E is opt-in (it installs into the local repository):"
						+ " pass -Drontolisp.jar.e2e=true");
		String mavenHome = System.getProperty("rontolisp.jar.e2e.maven.home");
		String localRepository = System.getProperty("rontolisp.jar.e2e.local.repository");
		assumeTrue(mavenHome != null && localRepository != null,
				"run through the root pom, whose surefire configuration names the Maven and the local repository");
		Path maven = Path.of(Objects.requireNonNull(mavenHome), "bin", "mvn");
		assumeTrue(Files.isExecutable(maven), "no Maven executable at " + maven);
		Ready ready = new Ready(maven, Path.of(Objects.requireNonNull(localRepository)),
				pinned("maven-resources-plugin"), pinned("maven-compiler-plugin"), pinned("maven-install-plugin"));
		// The install plugin runs only in the `install` phase, which `test` never
		// reaches,
		// and this test runs Maven offline.
		assumeTrue(
				Files.isRegularFile(ready.localRepository()
					.resolve("org/apache/maven/plugins/maven-install-plugin")
					.resolve(ready.installPlugin())
					.resolve("maven-install-plugin-" + ready.installPlugin() + ".jar")),
				"maven-install-plugin is not in the local repository, and this test runs Maven offline:"
						+ " run `./mvnw install -DskipTests` first");
		return ready;
	}

	private static String pinned(String artifactId) {
		String version = System.getProperty("rontolisp.jar.e2e." + artifactId);
		assumeTrue(version != null, "rontolisp.jar.e2e." + artifactId + " is unset");
		return Objects.requireNonNull(version);
	}

	/**
	 * The Maven running this test, the local repository it uses, and the version the root
	 * pom pins for each plugin the offline builds run.
	 */
	private record Ready(Path mavenExecutable, Path localRepository, String resourcesPlugin, String compilerPlugin,
			String installPlugin) {

		/**
		 * The fully qualified {@code install-file} goal at the pinned version. The
		 * {@code install:} prefix would resolve the version out of the plugin's remote
		 * metadata, which offline Maven cannot read.
		 */
		String installFileGoal() {
			return "org.apache.maven.plugins:maven-install-plugin:" + this.installPlugin + ":install-file";
		}

		List<String> maven(String... arguments) {
			List<String> command = new ArrayList<>();
			command.add(this.mavenExecutable.toString());
			command.add("-Dmaven.repo.local=" + this.localRepository);
			command.addAll(List.of(arguments));
			return command;
		}

	}

	private static Path javaExecutable() {
		return Path.of(System.getProperty("java.home"), "bin", "java");
	}

	private static String run(Path directory, List<String> command) throws Exception {
		Process process = new ProcessBuilder(command).directory(directory.toFile()).redirectErrorStream(true).start();
		String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
		int status = process.waitFor();
		assertThat(status).describedAs("%s exited %d:%n%s", command, status, output).isZero();
		return output;
	}

	private static void deleteRecursively(Path root) throws Exception {
		if (!Files.exists(root)) {
			return;
		}
		try (Stream<Path> tree = Files.walk(root)) {
			for (Path path : tree.sorted(Comparator.reverseOrder()).toList()) {
				Files.deleteIfExists(path);
			}
		}
	}

}
