(defun io-everything (path host)
  (let ((s (rontolisp:tcp-connect host 80)))
    (write-line "GET / HTTP/1.0" s)
    (write-string "x" s)
    (print (read-line s nil nil))
    (print (read-char s nil nil))
    (print (read-byte s nil nil))
    (write-byte 10 s)
    (print (rontolisp:tcp-local-port s))
    (print (rontolisp:tcp-local-address s))
    (print (rontolisp:tcp-peer-address s))
    (print (rontolisp:tcp-peer-port s))
    (rontolisp:tcp-set-timeout s 1000)
    (force-output s)
    (print (listen s))
    (print (open-stream-p s))
    (close s))
  (let ((l (rontolisp:tcp-listen 0)))
    (print (rontolisp:tcp-accept l)))
  (let ((tls (rontolisp:tls-connect host 443)))
    (close tls))
  (with-open-file (o path :direction :io :if-exists :overwrite :if-does-not-exist :create)
    (write-line "abc" o)
    (print (file-position o))
    (file-position o 0)
    (print (read-line o nil nil))
    (print (read-char o nil nil))
    (print (peek-char nil o nil nil))
    (print (read-byte o nil nil)))
  (with-open-file (o path :direction :output :if-exists :append)
    (write-line "def" o)
    (fresh-line o)
    (print (file-position o))
    (print (file-length o)))
  (with-open-file (i path :element-type '(unsigned-byte 8))
    (let ((buf (make-array 4 :element-type '(unsigned-byte 8))))
      (print (read-sequence buf i))
      (print (file-position i))))
  (with-open-file (i path)
    (let ((buf (make-string 4)))
      (print (read-sequence buf i))))
  (with-input-from-string (i "xyz")
    (print (listen i))
    (print (file-position i))
    (print (read-char i)))
  (print (with-output-to-string (o) (write-string "q" o)))
  (print (probe-file path))
  (print (file-write-date path))
  (print (directory "/tmp/*"))
  (ensure-directories-exist "/tmp/a86x/")
  (rename-file path "/tmp/a86y")
  (delete-file "/tmp/a86y")
  (write-line "err" *error-output*)
  (force-output *error-output*)
  (fresh-line *error-output*))
(io-everything "/tmp/a86z" "localhost")
