(defun io-no-err (path host)
  (let ((s (rontolisp:tcp-connect host 80)))
    (write-line "GET / HTTP/1.0" s)
    (write-string "x" s)
    (print (read-line s nil nil))
    (print (read-char s nil nil))
    (print (read-byte s nil nil))
    (write-byte 10 s)
    (force-output s)
    (print (listen s))
    (print (open-stream-p s))
    (close s))
  (with-open-file (o path :direction :output :if-exists :append)
    (write-line "def" o)
    (fresh-line o))
  (with-open-file (i path :element-type '(unsigned-byte 8))
    (let ((buf (make-array 4 :element-type '(unsigned-byte 8))))
      (print (read-sequence buf i))))
  (with-open-file (i path)
    (print (read-line i nil nil))
    (print (read-char i nil nil))
    (print (peek-char nil i nil nil)))
  (print (probe-file path)))
(io-no-err "/tmp/a86z" "localhost")
