(defun q (path)
  (let ((m (rontolisp:make-quantized-matrix 2 32)))
    (with-open-file (i path :element-type '(unsigned-byte 8))
      (print (read-sequence m i)))
    (with-open-file (o path :direction :output :element-type '(unsigned-byte 8) :if-exists :supersede)
      (write-sequence m o))
    (let ((v (make-array 4 :element-type 'single-float)))
      (with-open-file (i path :element-type '(unsigned-byte 8))
        (read-sequence v i)))))
(q "/tmp/a86q")
