(module
  (import "wasi:cli/stdout@0.2.0" "get-stdout" (func (result i32)))
  (import "wasi:io/streams@0.2.0" "[method]output-stream.blocking-write-and-flush" (func (param i32 i32 i32 i32)))
  (import "wasi:io/streams@0.2.0" "[method]input-stream.blocking-read" (func (param i32 i64 i32)))
  (import "wasi:io/streams@0.2.0" "[resource-drop]output-stream" (func (param i32)))
  (import "wasi:io/streams@0.2.0" "[resource-drop]input-stream" (func (param i32)))
  (import "wasi:random/random@0.2.0" "get-random-u64" (func (result i64)))
  (import "wasi:clocks/wall-clock@0.2.0" "now" (func (param i32)))
  (import "wasi:clocks/monotonic-clock@0.2.0" "now" (func (result i64)))
  (import "wasi:cli/environment@0.2.0" "get-environment" (func (param i32)))
  (import "wasi:filesystem/types@0.2.0" "[method]descriptor.open-at" (func (param i32 i32 i32 i32 i32 i32 i32)))
  (import "wasi:filesystem/types@0.2.0" "[method]descriptor.read-via-stream" (func (param i32 i64 i32)))
  (import "wasi:filesystem/types@0.2.0" "[method]descriptor.write-via-stream" (func (param i32 i64 i32)))
  (import "wasi:filesystem/types@0.2.0" "[resource-drop]descriptor" (func (param i32)))
  (import "wasi:filesystem/preopens@0.2.0" "get-directories" (func (param i32)))
  (import "wasi:cli/stdin@0.2.0" "get-stdin" (func (result i32)))
  ;; --- outgoing HTTP (rontolisp:fetch), component mode only ---
  (import "wasi:io/poll@0.2.0" "[method]pollable.block" (func (param i32)))
  (import "wasi:io/poll@0.2.0" "[resource-drop]pollable" (func (param i32)))
  (import "wasi:http/types@0.2.0" "[constructor]fields" (func (result i32)))
  (import "wasi:http/types@0.2.0" "[method]fields.append" (func (param i32 i32 i32 i32 i32 i32)))
  (import "wasi:http/types@0.2.0" "[method]fields.entries" (func (param i32 i32)))
  (import "wasi:http/types@0.2.0" "[constructor]outgoing-request" (func (param i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]outgoing-request.set-method" (func (param i32 i32 i32 i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]outgoing-request.set-scheme" (func (param i32 i32 i32 i32 i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]outgoing-request.set-authority" (func (param i32 i32 i32 i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]outgoing-request.set-path-with-query" (func (param i32 i32 i32 i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[resource-drop]fields" (func (param i32)))
  (import "wasi:http/types@0.2.0" "[resource-drop]outgoing-request" (func (param i32)))
  (import "wasi:http/types@0.2.0" "[resource-drop]future-incoming-response" (func (param i32)))
  (import "wasi:http/types@0.2.0" "[resource-drop]incoming-response" (func (param i32)))
  (import "wasi:http/types@0.2.0" "[resource-drop]incoming-body" (func (param i32)))
  (import "wasi:http/types@0.2.0" "[method]future-incoming-response.subscribe" (func (param i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]future-incoming-response.get" (func (param i32 i32)))
  (import "wasi:http/types@0.2.0" "[method]incoming-response.status" (func (param i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]incoming-response.headers" (func (param i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]incoming-response.consume" (func (param i32 i32)))
  (import "wasi:http/types@0.2.0" "[method]incoming-body.stream" (func (param i32 i32)))
  ;; Request body support (rontolisp:fetch :body). outgoing-request.body and
  ;; outgoing-body.write return result<own<...>> via a return pointer; outgoing-body.finish
  ;; is a static method taking the body plus an option<trailers> and a result return ptr.
  (import "wasi:http/types@0.2.0" "[method]outgoing-request.body" (func (param i32 i32)))
  (import "wasi:http/types@0.2.0" "[method]outgoing-body.write" (func (param i32 i32)))
  (import "wasi:http/types@0.2.0" "[static]outgoing-body.finish" (func (param i32 i32 i32 i32)))
  (import "wasi:http/types@0.2.0" "[resource-drop]outgoing-body" (func (param i32)))
  (import "wasi:http/outgoing-handler@0.2.0" "handle" (func (param i32 i32 i32 i32)))
  (memory (export "memory") 16)
  (global $hp (mut i32) (i32.const 65536))
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) (global.get $hp))
  (func (export "run") (result i32) (i32.const 0)))
