;; Stub core whose only purpose is to make `wasm-tools component new` emit the imports for
;; import-block-http-client.bin. Imports every lowered function the http-variant adapter binds:
;; the WASI 0.3 base functions (same as core.wat) plus the WASI 0.2 HTTP / io machinery for
;; rontolisp:fetch. Exports a memory (16 pages, for the fetch header/body scratch) +
;; cabi_realloc + run.
(module
  ;; --- base I/O: WASI 0.3 (identical to core.wat) ---
  (import "wasi:cli/stdout@0.3.0" "write-via-stream" (func (param i32) (result i32)))
  (import "wasi:cli/stdin@0.3.0" "read-via-stream" (func (param i32)))
  (import "wasi:cli/environment@0.3.0" "get-environment" (func (param i32)))
  (import "wasi:clocks/system-clock@0.3.0" "now" (func (param i32)))
  (import "wasi:clocks/monotonic-clock@0.3.0" "now" (func (result i64)))
  (import "wasi:filesystem/types@0.3.0" "[method]descriptor.read-via-stream" (func (param i32 i64 i32)))
  (import "wasi:filesystem/types@0.3.0" "[method]descriptor.append-via-stream" (func (param i32 i32) (result i32)))
  (import "wasi:filesystem/types@0.3.0" "[method]descriptor.open-at" (func (param i32 i32 i32 i32 i32 i32 i32)))
  (import "wasi:filesystem/preopens@0.3.0" "get-directories" (func (param i32)))
  (import "wasi:random/random@0.3.0" "get-random-u64" (func (result i64)))
  ;; --- outgoing HTTP (rontolisp:fetch): WASI 0.2 ---
  ;; io/poll + io/streams drive the request/response body over wasi:http@0.2.
  (import "wasi:io/poll@0.2.0" "[method]pollable.block" (func (param i32)))
  (import "wasi:io/poll@0.2.0" "[resource-drop]pollable" (func (param i32)))
  (import "wasi:io/streams@0.2.0" "[method]output-stream.blocking-write-and-flush" (func (param i32 i32 i32 i32)))
  (import "wasi:io/streams@0.2.0" "[method]input-stream.blocking-read" (func (param i32 i64 i32)))
  (import "wasi:io/streams@0.2.0" "[resource-drop]output-stream" (func (param i32)))
  (import "wasi:io/streams@0.2.0" "[resource-drop]input-stream" (func (param i32)))
  ;; http/types: request/response machinery
  (import "wasi:http/types@0.2.0" "[constructor]fields" (func (result i32)))
  (import "wasi:http/types@0.2.0" "[method]fields.append" (func (param i32 i32 i32 i32 i32 i32)))
  (import "wasi:http/types@0.2.0" "[method]fields.entries" (func (param i32 i32)))
  (import "wasi:http/types@0.2.0" "[constructor]outgoing-request" (func (param i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]outgoing-request.set-method" (func (param i32 i32 i32 i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]outgoing-request.set-scheme" (func (param i32 i32 i32 i32 i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]outgoing-request.set-authority" (func (param i32 i32 i32 i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]outgoing-request.set-path-with-query" (func (param i32 i32 i32 i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]outgoing-request.body" (func (param i32 i32)))
  (import "wasi:http/types@0.2.0" "[method]outgoing-body.write" (func (param i32 i32)))
  (import "wasi:http/types@0.2.0" "[static]outgoing-body.finish" (func (param i32 i32 i32 i32)))
  (import "wasi:http/types@0.2.0" "[method]future-incoming-response.subscribe" (func (param i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]future-incoming-response.get" (func (param i32 i32)))
  (import "wasi:http/types@0.2.0" "[method]incoming-response.status" (func (param i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]incoming-response.headers" (func (param i32) (result i32)))
  (import "wasi:http/types@0.2.0" "[method]incoming-response.consume" (func (param i32 i32)))
  (import "wasi:http/types@0.2.0" "[method]incoming-body.stream" (func (param i32 i32)))
  (import "wasi:http/types@0.2.0" "[resource-drop]fields" (func (param i32)))
  (import "wasi:http/types@0.2.0" "[resource-drop]outgoing-request" (func (param i32)))
  (import "wasi:http/types@0.2.0" "[resource-drop]outgoing-body" (func (param i32)))
  (import "wasi:http/types@0.2.0" "[resource-drop]future-incoming-response" (func (param i32)))
  (import "wasi:http/types@0.2.0" "[resource-drop]incoming-response" (func (param i32)))
  (import "wasi:http/types@0.2.0" "[resource-drop]incoming-body" (func (param i32)))
  (import "wasi:http/outgoing-handler@0.2.0" "handle" (func (param i32 i32 i32 i32)))
  (import "wasi:cli/stderr@0.3.0" "write-via-stream" (func (param i32) (result i32)))
  (memory (export "memory") 16)
  (global $hp (mut i32) (i32.const 65536))
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) (global.get $hp))
  (func (export "run") (result i32) (i32.const 0)))
