(module
  (import "wasi:cli/stdout@0.2.0" "get-stdout" (func (result i32)))
  (import "wasi:io/streams@0.2.0" "[method]output-stream.blocking-write-and-flush" (func (param i32 i32 i32 i32)))
  (import "wasi:io/streams@0.2.0" "[method]input-stream.blocking-read" (func (param i32 i64 i32)))
  (import "wasi:io/streams@0.2.0" "[resource-drop]output-stream" (func (param i32)))
  (import "wasi:io/streams@0.2.0" "[resource-drop]input-stream" (func (param i32)))
  (import "wasi:random/random@0.2.0" "get-random-u64" (func (result i64)))
  (import "wasi:clocks/wall-clock@0.2.0" "now" (func (param i32)))
  (import "wasi:clocks/monotonic-clock@0.2.0" "now" (func (result i64)))
  (import "wasi:cli/environment@0.2.0" "get-environment" (func (param i32)))
  (import "wasi:filesystem/types@0.2.0" "[method]descriptor.open-at" (func (param i32 i32 i32 i32 i32 i32 i32)))
  (import "wasi:filesystem/types@0.2.0" "[method]descriptor.read-via-stream" (func (param i32 i64 i32)))
  (import "wasi:filesystem/types@0.2.0" "[method]descriptor.write-via-stream" (func (param i32 i64 i32)))
  (import "wasi:filesystem/types@0.2.0" "[resource-drop]descriptor" (func (param i32)))
  (import "wasi:filesystem/preopens@0.2.0" "get-directories" (func (param i32)))
  (import "wasi:cli/stdin@0.2.0" "get-stdin" (func (result i32)))
  (memory (export "memory") 6)
  (global $hp (mut i32) (i32.const 65536))
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) (global.get $hp))
  (func (export "run") (result i32) (i32.const 0)))
