// GENERATED by rontolisp --emit-js-glue -- do not edit.
//
// The host half of this module's boundary, derived from the program's own
// declarations: one import-object entry per rontolisp:wasm-import, one entry
// point per rontolisp:wasm-export, and every piece of linear-memory plumbing
// between them -- the (ptr, len) pair a :string crosses as and the __ronto_alloc
// bracket around a call.
//
// What a declaration cannot state is what a host function DOES, so that is the
// one thing this file asks for: `host` is a plain function per import, keyed by
// import module and field, taking and answering ordinary JavaScript values --
// never a (ptr, len) pair.
//
//   import { instantiate, suspending } from "./worker.js";
//
//   const lisp = instantiate(module, {
//     env: {
//       fetch: (text) => text,   // or leave it to defaultHost()
//     },
//   });
//   await lisp.handleRequest(text);
//
// A host that suspends marks its own entries -- suspending(async (...) => ...)
// -- and every entry point above then answers a promise: the marked imports are
// wrapped in WebAssembly.Suspending, each entry point that can reach one is
// entered through WebAssembly.promising, and calls are serialised onto one
// promise chain, because a suspended module returns to the host's event loop
// and a re-entered export refuses with a trap rather than corrupting both
// calls. Host state that belongs to ONE such call is set inside that section:
//
//   await lisp.serially(async (entry) => { ...; return entry.handleRequest(...) });
//
// This module's boundary is the reactor envelope, so the Request/Response half
// is derivable too and `worker` below is it:
//
//   import module from "./worker.wasm";
//   import { worker } from "./worker.js";
//
//   export default worker(module);
//
// Regenerate it, never edit it: --emit-js-glue on the compile that wrote the
// .wasm beside it.

const encoder = new TextEncoder();
// ignoreBOM, because these octets are a VALUE and not a document: a
// leading U+FEFF is a character the other side chose, and the default
// decoder deletes it -- silently shortening a BOM-prefixed request body
// by one character while the content-length beside it still counts three.
const decoder = new TextDecoder("utf-8", { ignoreBOM: true });

const SUSPENDING = Symbol.for("rontolisp.suspending");

/**
 * Marks a host function as one that answers a promise, so the wasm stack parks
 * until it settles (JSPI). The wrapper is not free -- an import answering
 * SYNCHRONOUSLY through one still returns to the event loop -- so mark only the
 * entries this host really implements asynchronously.
 *
 * @param {Function} fn the host function
 * @returns {object} the marked entry, to be passed as the import
 */
export function suspending(fn) {
  return { [SUSPENDING]: fn };
}

/**
 * Instantiates the module against this host and returns its callable surface.
 *
 * @param {WebAssembly.Module} module the compiled module
 * @param {object} host one function per import, keyed by module and field
 * @returns {object} `exports`, plus one entry point per rontolisp:wasm-export
 */
export function instantiate(module, host = {}) {
  let exports;

  // Every view is built where it is used, never held: growing the module's
  // memory DETACHES the buffer behind every view taken before the growth, and a
  // suspending host resumes after growths it never saw.
  const readString = (ptr, len) =>
    decoder.decode(new Uint8Array(exports.memory.buffer, ptr, len));

  // Bytes the HOST hands over live in the module's own bump allocator, and
  // cross as the (ptr, len) pair every memory-typed value is.
  const write = (octets) => {
    const ptr = exports.__ronto_alloc(octets.length);
    new Uint8Array(exports.memory.buffer, ptr, octets.length).set(octets);
    return [ptr, octets.length];
  };
  const writeString = (value) => write(encoder.encode(String(value)));

  // A host answers a value, or -- from an entry it marked suspending -- a promise
  // of one. Both shapes ride one expression, which is what lets this file drive a
  // synchronous host and a JSPI host without being written twice.
  const marked = new Set();
  const unmarked = (what) =>
    what +
    " answered a promise; wrap it in suspending() so the wasm stack parks" +
    " until it settles";
  const settle = (what, value, next) => {
    if (typeof value?.then === "function") {
      if (!marked.has(what)) {
        // Reported before it is thrown: this throw crosses back into wasm,
        // where a catch_all landing pad turns it into whatever the module
        // makes of a failed import.
        console.error(unmarked(what));
        throw new TypeError(unmarked(what));
      }
      return value.then(next);
    }
    return next(value);
  };

  // The entries the module really imports: --optimize shakes out an import the
  // program never calls, and a host should not have to know which survived.
  const linked = new Set(
    WebAssembly.Module.imports(module).map((i) => i.module + "." + i.name),
  );
  const bind = (moduleName, field, wrap) => {
    const key = moduleName + "." + field;
    const given = (host[moduleName] ?? {})[field];
    if (given == null) {
      if (!linked.has(key)) return undefined;
      throw new TypeError("host." + key + " is missing; this module imports it");
    }
    if (given[SUSPENDING] === undefined) {
      // An async function that was never marked is the one mistake worth
      // catching HERE, where the report is a plain stack and not whatever
      // the module makes of an import that threw.
      if (given.constructor?.name === "AsyncFunction") {
        throw new TypeError(unmarked("host." + key));
      }
      return wrap(key, given);
    }
    marked.add(key);
    return new WebAssembly.Suspending(wrap(key, given[SUSPENDING]));
  };

  const imports = {
    env: {
      // (:string) -> :string
      fetch: bind("env", "fetch", (what, call) => {
        return (p0, p0Len) =>
          settle(what, call(readString(p0, p0Len)), writeString);
      }),
    },
  };
  const instance = new WebAssembly.Instance(module, imports);
  exports = instance.exports;
  // Entropy, BEFORE the top level runs: a --no-wasi module imports none, so its
  // `random` starts from a constant and every instance would draw one sequence.
  // Seeding here also covers the draws a library makes while it LOADS. A Worker
  // forbids this in global scope, so instantiate on the first request.
  exports.__ronto_seed_random(
    new BigUint64Array(crypto.getRandomValues(new Uint8Array(8)).buffer)[0],
  );
  // And a clock, nanoseconds since the Unix epoch, for the same reason and
  // before the same line: until one is set the clock built-ins signal rather
  // than report 1970.
  exports.__ronto_set_time(BigInt(Date.now()) * 1000000n);
  exports._initialize();

  // The entry points a call chain can reach a suspending import from -- the
  // list the build prints -- entered through WebAssembly.promising exactly when
  // the host marked one. An unmarked host never pays for the promise.
  const suspends = marked.size !== 0;
  const entry$handleRequest = suspends
    ? WebAssembly.promising(exports["handle-request"])
    : exports["handle-request"];

  // One Lisp call at a time. A suspended call returns to the host's event loop,
  // and the module's own re-entry guard TRAPS a second entry rather than let two
  // calls share its allocator and its dynamic bindings -- so the queue is the
  // contract, not a nicety. `.then(work, work)` because one rejected call must
  // not wedge the chain behind it.
  let queue = Promise.resolve();
  const queued = (work) => {
    const done = queue.then(work, work);
    queue = done.then(
      () => {},
      () => {},
    );
    return done;
  };
  // A bare entry point only needs the queue when a host marked something: a
  // synchronous call cannot be interleaved, and paying a promise for it would
  // make every host asynchronous. `serially` below always takes it, because
  // the work it runs awaits and a second request WOULD land inside it.
  const serialised = (work) => (suspends ? queued(work) : work());

  // One call into the module: stage the arguments, enter, decode the result out
  // of the scratch it sits in, and only THEN pop the arena that scratch is in.
  // A promising entry answers a promise, so the tail rides `then`; a synchronous
  // one runs the same expression inline. `run` is how the call reaches the
  // module -- through the queue, or straight through when it is already inside
  // the one call the queue admits.
  const call = (run, entry, stage, decode) => {
    const work = () => {
      // The module's clock moves only when the host moves it, so move it per
      // call. Not a workaround for a frozen clock -- a Worker's own Date.now()
      // is frozen for the duration of a request as a timing-attack mitigation,
      // so a value that changes once per call is what the platform has.
      exports.__ronto_set_time(BigInt(Date.now()) * 1000000n);
      const mark = exports.__ronto_alloc_mark();
      const done = (raw) => {
        const value = decode(raw);
        exports.__ronto_alloc_reset(mark);
        return value;
      };
      // A TRAP skips the pop above and leaves the module's state half-written
      // with it, so a host that keeps serving instantiates again rather than
      // calling back into this instance.
      const raw = entry(...stage());
      return typeof raw?.then === "function" ? raw.then(done) : done(raw);
    };
    return run(work);
  };

  /** `handle-request` -- (:string) -> :string */
  const make$handleRequest =
    (run) =>
    (p0) => {
      return call(
        run,
        entry$handleRequest,
        () => {
          const a0 = writeString(p0);
          return [a0[0], a0[1]];
        },
        ([ptr, len]) => readString(ptr, len),
      );
    };


  // Host state that belongs to ONE call -- what the module pulls DURING it,
  // and what the call leaves behind -- is set and read inside `work`, which
  // runs in the same critical section: a suspended call returns to the event
  // loop, so setting it beside the call instead would let the next request
  // move it under this one. The entry points `work` is handed enter the module
  // directly, because the queue they would take is the one they are in.
  const inside = {
    handleRequest: make$handleRequest((work) => work()),
  };
  const serially = (work) => queued(() => work(inside));

  return {
    exports,
    handleRequest: make$handleRequest(serialised),
    serially,
  };
}

/**
 * The half of this boundary the module's own declarations FIX, ready to hand to
 * `instantiate` -- or to leave to `worker` below, which passes it for you. What
 * a host is still free to do is override it: whatever it supplies wins, entry by
 * entry.
 *
 * @returns {object} the import-object entries this file implements itself
 */
export function defaultHost() {
  return {
    env: {
      fetch: suspending(async (head) => {
        const request = JSON.parse(head);
        try {
          const response = await fetch(request.url, {
            method: request.method,
            headers: request.headers,
            body: request.body,
          });
          return JSON.stringify({
            status: response.status,
            headers: [...response.headers],
            body: await response.text(),
          });
        } catch (error) {
          // The error arm becomes a Lisp condition at the fetch CALL; throwing
          // here would trap the instance instead, and take the request with it.
          return JSON.stringify({ error: String(error) });
        }
      }),
    },
  };
}

/**
 * This module as a fetch handler -- the whole Worker, with nothing left over:
 *
 *   import module from "./worker.wasm";
 *   import { worker } from "./worker.js";
 *
 *   export default worker(module);
 *
 * A Request becomes the envelope the module's entry point takes, the head it
 * answers becomes a Response, and the instance is created on the FIRST REQUEST
 * (a Worker forbids drawing entropy in global scope) and retired if a call ever
 * traps.
 *
 * @param {WebAssembly.Module} module the compiled module
 * @param {object} [options] `host` -- import entries, laid over defaultHost()'s
 *   one at a time; `remoteAddr` -- (request, env, ctx) => the client
 *   address, since which header carries it is the platform's business and not
 *   this file's (`(r) => r.headers.get("cf-connecting-ip")` on Cloudflare)
 * @returns {object} `{ fetch(request, env, ctx) }`
 */
export function worker(module, options = {}) {
  let instance = null;
  // Set when a call TRAPPED: that instance skipped its arena reset and its Lisp
  // state may be half-written, so nothing else may run on it. A Lisp ERROR is not
  // this -- the transport answers 500 itself and the instance is fine.
  let poisoned = false;
  const base = defaultHost();
  const given = options.host ?? {};
  const host = {};
  for (const key of new Set([...Object.keys(base), ...Object.keys(given)])) {
    host[key] = { ...(base[key] ?? {}), ...(given[key] ?? {}) };
  }
  const live = () => {
    if (poisoned) {
      instance = null;
      poisoned = false;
    }
    return (instance ??= instantiate(module, host));
  };

  // The request head. `target` stays RAW -- path and query still joined and
  // still percent-encoded -- because the shared normalizer on the other side
  // owns that split, and a pre-split path leaves the query string nil.
  const envelope = (request, octets, remoteAddr) => {
    const url = new URL(request.url);
    const headers = Object.fromEntries(request.headers);
    // A body with no content-length is a body the request parser does not read,
    // and a chunked request carries none -- so set it from the octets we have.
    if (octets?.length) headers["content-length"] = String(octets.length);
    const head = {
      method: request.method,
      target: url.pathname + url.search,
      headers,
      scheme: url.protocol.replace(":", ""),
    };
    if (octets?.length) head.body = decoder.decode(octets);
    if (remoteAddr != null) head["remote-addr"] = remoteAddr;
    return JSON.stringify(head);
  };

  return {
    // EVERYTHING is inside the try, not just the module call: reading an
    // aborted upload rejects, and `new Response` throws on a status or a
    // header an application is free to produce (0, 999, a newline in a
    // value). Outside it those escape as an unhandled rejection, which the
    // platform answers with its own error page and nothing in the log.
    async fetch(request, env, ctx) {
      let entered = false;
      try {
        const remoteAddr = await options.remoteAddr?.(request, env, ctx);
        const octets = request.body
          ? new Uint8Array(await request.arrayBuffer())
          : null;
        const input = envelope(request, octets, remoteAddr);
        const head = JSON.parse(
          await live().serially((lisp) => {
            // Re-read INSIDE the critical section: the instance was bound at
            // admission, and a call parked ahead of this one can poison it
            // before this one runs. Refusing is the whole point -- a
            // half-unwound instance answers wrong rather than failing, and
            // the module's own re-entry guard is cleared by the landing pad
            // on exactly the path that poisons it.
            if (poisoned) throw new Error("instance discarded by an earlier trap");
            entered = true;
            return lisp.handleRequest(input);
          }),
        );
        // Headers as an ARRAY of pairs, which keeps two Set-Cookie two.
        // An EMPTY body becomes null whichever shape it arrived in: 204/205/304
        // may only be constructed with a null body, and "" and a zero-length
        // Uint8Array are the same response as none.
        const body = head.body;
        return new Response(body?.length ? body : null, {
          status: head.status ?? 200,
          headers: head.headers ?? [],
        });
      } catch (error) {
        console.error("handle-request failed:", error);
        // Only a call that ENTERED the module can have left it half-written.
        // A mapping, or a Response the platform refused, says nothing about
        // the instance, and discarding it would cost the next request a
        // reinstantiation for someone else's bad header.
        if (entered) poisoned = true;
        return new Response("internal error\n", { status: 500 });
      }
    },
  };
}
