package am.ik.rontolisp.cli;

import java.util.regex.Pattern;

import am.ik.rontolisp.Version;

/**
 * The {@code groupId:artifactId:version} a {@code -o out.jar} build stamps into its own
 * artifact ({@code --maven-coordinates}).
 * <p>
 * The coordinates travel INSIDE the jar, as the
 * {@code META-INF/maven/<groupId>/<artifactId>/pom.xml} + {@code pom.properties} pair
 * every Maven-built jar already carries. That is what lets a consumer run
 * {@code mvn install:install-file -Dfile=out.jar} with no {@code -DgroupId} /
 * {@code -DartifactId} / {@code -Dversion} / {@code -DpomFile}: Maven reads them back out
 * of the artifact.
 * <p>
 * A rontolisp-compiled class has no dependencies -- the acceleration bridges and the
 * {@code :float-vector} handle class both travel inside the artifact -- so the generated
 * pom's {@code <dependencies>} is genuinely empty, and it is written empty rather than
 * omitted so that the property is visible in the file.
 */
record MavenCoordinates(String groupId, String artifactId, String version) {

	/**
	 * What a generated pom starts with, so {@code --emit-pom} can tell a file it wrote
	 * before from one the build owns. Version-free on purpose: an upgrade must still
	 * recognize the pom the previous release wrote.
	 */
	static final String POM_MARKER = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- Generated by rontolisp";

	// Maven's own allowed shape for a group/artifact id, and the shape that is also safe
	// both as an XML text node and as a jar entry path -- the two places these strings
	// land unescaped.
	private static final Pattern ID = Pattern.compile("[A-Za-z0-9_][A-Za-z0-9_.-]*");

	private static final Pattern VERSION = Pattern.compile("[A-Za-z0-9_][A-Za-z0-9_.+-]*");

	/**
	 * Parses a {@code groupId:artifactId:version} spec.
	 * @param spec the coordinate spec as written on the command line
	 * @return the parsed coordinates
	 * @throws IllegalArgumentException if the spec is not three well-formed parts
	 */
	static MavenCoordinates parse(String spec) {
		String[] parts = spec.split(":", -1);
		if (parts.length != 3) {
			throw new IllegalArgumentException("--maven-coordinates takes groupId:artifactId:version ('" + spec
					+ "' has " + parts.length + " part" + (parts.length == 1 ? "" : "s") + ")");
		}
		require(ID, parts[0], "groupId", spec);
		require(ID, parts[1], "artifactId", spec);
		require(VERSION, parts[2], "version", spec);
		return new MavenCoordinates(parts[0], parts[1], parts[2]);
	}

	private static void require(Pattern pattern, String value, String part, String spec) {
		if (!pattern.matcher(value).matches()) {
			throw new IllegalArgumentException("--maven-coordinates " + part + " '" + value + "' is not a legal Maven "
					+ part + " (spec '" + spec + "'): letters, digits, '_', '.', '-' only");
		}
	}

	/** The directory the two metadata files live in, inside the jar. */
	String metaInfDirectory() {
		return "META-INF/maven/" + this.groupId + "/" + this.artifactId + "/";
	}

	/**
	 * The generated pom. {@code <dependencies>} is empty because the artifact really has
	 * none; the description carries the one thing a consumer's build has to know, which
	 * is whether the kernels inside need {@code --add-modules jdk.incubator.vector}.
	 * @param simd whether the class was compiled with {@code --simd}
	 * @return the pom XML
	 */
	String pomXml(boolean simd) {
		return POM_MARKER + " " + Version.getVersion() + ". -->\n"
				+ "<project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n"
				+ "         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
				+ "         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0"
				+ " http://maven.apache.org/xsd/maven-4.0.0.xsd\">\n" //
				+ "  <modelVersion>4.0.0</modelVersion>\n" //
				+ "  <groupId>" + this.groupId + "</groupId>\n" //
				+ "  <artifactId>" + this.artifactId + "</artifactId>\n" //
				+ "  <version>" + this.version + "</version>\n" //
				+ "  <packaging>jar</packaging>\n" //
				+ "  <description>" + description(simd) + "</description>\n"
				+ "  <!-- A rontolisp-compiled class embeds everything it calls, so this artifact"
				+ " really has no dependencies. -->\n" //
				+ "  <dependencies/>\n" //
				+ "</project>\n";
	}

	private static String description(boolean simd) {
		String base = "Compiled from Lisp by rontolisp. Self-contained: no dependencies.";
		// Not a requirement -- a class without the module degrades to the portable
		// scalar kernels and says so -- but the consumer never saw the build command,
		// so the pom is the only place that can tell them the flag is worth passing.
		return simd ? base + " Built with --simd: run the consumer's JVM with"
				+ " --add-modules jdk.incubator.vector to get the vector kernels;"
				+ " without it the class runs the portable scalar reference." : base;
	}

	/**
	 * The {@code pom.properties} beside the pom. Maven writes a build timestamp comment
	 * into its own; this one leaves it out, because the emitted artifact must be a
	 * function of the program and not of the run
	 * ({@code .kb/emitted-output-determinism.md}).
	 * @return the properties text
	 */
	String pomProperties() {
		return "groupId=" + this.groupId + "\n" //
				+ "artifactId=" + this.artifactId + "\n" //
				+ "version=" + this.version + "\n";
	}

}
