//! The Rust shouter -- one component on BOTH sides of the WIT boundary.
//!
//! It EXPORTS the `shout` interface (the Lisp app calls `emphasize`) and IMPORTS
//! the `vowel-count` function (a Lisp component supplies it). So a single call to
//! `emphasize` is Lisp -> Rust -> Lisp: Rust uppercases the text and asks Lisp to
//! count the vowels, to decide how many `!` to append. `mod bindings` is
//! generated by cargo-component from ../wit (see Cargo.toml).

#[allow(warnings)]
mod bindings;

use bindings::exports::example::pipeline::shout::Guest;
use bindings::vowel_count;

struct Component;

impl Guest for Component {
    fn emphasize(text: String) -> String {
        // Rust -> Lisp: the imported `vowel-count` is an ordinary function call.
        let vowels = vowel_count(&text);
        let mut out = text.to_uppercase();
        for _ in 0..vowels.max(0) {
            out.push('!');
        }
        out
    }
}

bindings::export!(Component with_types_in bindings);
