//! The Rust describer. It EXPORTS `describe` and, to do its job, IMPORTS
//! `vowel-count` from a Lisp component -- so calling `describe` is Rust -> Lisp.
//!
//! Rust does the sentence building; Lisp does the counting. The host (or another
//! component) calls `describe`; nothing here knows the counter is written in
//! Lisp -- only the WIT does. `mod bindings` is generated by cargo-component from
//! ../wit (see Cargo.toml); `cargo component build` regenerates it.

#[allow(warnings)]
mod bindings;

use bindings::exports::example::vowels::describe::Guest;
use bindings::vowel_count;

struct Component;

impl Guest for Component {
    fn describe(text: String) -> String {
        // Rust -> Lisp: the imported `vowel-count` is an ordinary function call.
        let n = vowel_count(&text);
        let plural = if n == 1 { "" } else { "s" };
        format!("\"{text}\" has {n} vowel{plural}")
    }
}

bindings::export!(Component with_types_in bindings);
