package am.ik.rontolisp.codegen.wasm;

import am.ik.wit.Wit;
import am.ik.wit.WitDocument;
import am.ik.wit.WitItem;

import static am.ik.wit.Wit.*;

/**
 * The fixed WIT worlds of the {@code --component} blob variants -- the world's WASI
 * imports, the fixed {@code wasi:cli/run} / {@code wasi:http/incoming-handler} export and
 * the referenced (reachability-pruned) package definitions -- as document models for
 * {@link WitEmitter}. Byte-equality of the canonical print with
 * {@code wasm-tools component wit} is pinned per variant by
 * {@code WasiWitDefinitionsTest} against the fixtures under
 * {@code src/test/resources/.../component/wit/}.
 *
 * <p>
 * GENERATED by {@code WasiWitDefinitionsGenerator} from those fixtures -- after changing
 * a blob's import surface, re-run {@code src/wasm-component/regen-wit.sh} and the
 * generator instead of editing this file (see {@code src/wasm-component/README.md}).
 */
final class WasiWitDefinitions {

	private WasiWitDefinitions() {
	}

	/**
	 * The fixed WIT document of a blob variant.
	 * @param variant one of the {@code WitEmitter.VARIANT_*} names
	 * @return the document (package header, world, package definitions)
	 */
	static WitDocument document(String variant) {
		return switch (variant) {
			case WitEmitter.VARIANT_BASE -> base();
			case WitEmitter.VARIANT_HTTP_CLIENT -> httpClient();
			case WitEmitter.VARIANT_SOCKETS -> sockets();
			case WitEmitter.VARIANT_HTTP_SERVER -> httpServer();
			case WitEmitter.VARIANT_HTTP_SERVER_CLIENT -> httpServerClient();
			case WitEmitter.VARIANT_NOGC -> nogc();
			case WitEmitter.VARIANT_NOGC_PRINT -> nogcPrint();
			default -> throw new IllegalStateException("Missing WIT definition for variant: " + variant);
		};
	}

	private static WitDocument base() {
		return Wit.document(packageHeader("root", "component", null), world("root",
				importRef(ref("wasi", "cli", "types", "0.3.0")), importRef(ref("wasi", "cli", "stdout", "0.3.0")),
				importRef(ref("wasi", "cli", "stdin", "0.3.0")), importRef(ref("wasi", "cli", "environment", "0.3.0")),
				importRef(ref("wasi", "clocks", "system-clock", "0.3.0")),
				importRef(ref("wasi", "clocks", "monotonic-clock", "0.3.0")),
				importRef(ref("wasi", "filesystem", "types", "0.3.0")),
				importRef(ref("wasi", "filesystem", "preopens", "0.3.0")),
				importRef(ref("wasi", "random", "random", "0.3.0")), importRef(ref("wasi", "cli", "stderr", "0.3.0")),
				exportRef(ref("wasi", "cli", "run", "0.3.0"))), wasiCliV030(), wasiClocksV030(), wasiFilesystemV030(),
				wasiRandomV030());
	}

	private static WitDocument httpClient() {
		return Wit.document(packageHeader("root", "component", null), world("root",
				importRef(ref("wasi", "cli", "types", "0.3.0")), importRef(ref("wasi", "cli", "stdout", "0.3.0")),
				importRef(ref("wasi", "cli", "stdin", "0.3.0")), importRef(ref("wasi", "cli", "environment", "0.3.0")),
				importRef(ref("wasi", "clocks", "system-clock", "0.3.0")),
				importRef(ref("wasi", "clocks", "monotonic-clock", "0.3.0")),
				importRef(ref("wasi", "filesystem", "types", "0.3.0")),
				importRef(ref("wasi", "filesystem", "preopens", "0.3.0")),
				importRef(ref("wasi", "random", "random", "0.3.0")), importRef(ref("wasi", "io", "poll", "0.2.0")),
				importRef(ref("wasi", "io", "error", "0.2.0")), importRef(ref("wasi", "io", "streams", "0.2.0")),
				importRef(ref("wasi", "http", "types", "0.2.0")),
				importRef(ref("wasi", "http", "outgoing-handler", "0.2.0")),
				importRef(ref("wasi", "cli", "stderr", "0.3.0")), exportRef(ref("wasi", "cli", "run", "0.3.0"))),
				wasiCliV030(), wasiClocksV030(), wasiFilesystemV030(), wasiRandomV030(), wasiIoV020(), wasiHttpV020());
	}

	private static WitDocument sockets() {
		return Wit.document(packageHeader("root", "component", null), world("root",
				importRef(ref("wasi", "cli", "types", "0.3.0")), importRef(ref("wasi", "cli", "stdout", "0.3.0")),
				importRef(ref("wasi", "cli", "stdin", "0.3.0")), importRef(ref("wasi", "cli", "environment", "0.3.0")),
				importRef(ref("wasi", "clocks", "system-clock", "0.3.0")),
				importRef(ref("wasi", "clocks", "monotonic-clock", "0.3.0")),
				importRef(ref("wasi", "filesystem", "types", "0.3.0")),
				importRef(ref("wasi", "filesystem", "preopens", "0.3.0")),
				importRef(ref("wasi", "random", "random", "0.3.0")),
				importRef(ref("wasi", "sockets", "types", "0.3.0")), importRef(ref("wasi", "cli", "stderr", "0.3.0")),
				exportRef(ref("wasi", "cli", "run", "0.3.0"))), wasiCliV030(), wasiClocksV030(), wasiFilesystemV030(),
				wasiRandomV030(), wasiSocketsV030());
	}

	private static WitDocument httpServer() {
		return Wit.document(packageHeader("root", "component", null), world("root",
				importRef(ref("wasi", "clocks", "monotonic-clock", "0.2.0")),
				importRef(ref("wasi", "io", "error", "0.2.0")), importRef(ref("wasi", "io", "streams", "0.2.0")),
				importRef(ref("wasi", "http", "types", "0.2.0")), importRef(ref("wasi", "random", "random", "0.2.0")),
				importRef(ref("wasi", "clocks", "wall-clock", "0.2.0")),
				importRef(ref("wasi", "cli", "stdout", "0.2.0")), importRef(ref("wasi", "cli", "stderr", "0.2.0")),
				exportRef(ref("wasi", "http", "incoming-handler", "0.2.0"))), wasiClocksV020(), wasiIoV020HttpServer(),
				wasiHttpV020HttpServer(), wasiRandomV020(), wasiCliV020());
	}

	private static WitDocument httpServerClient() {
		return Wit.document(packageHeader("root", "component", null), world("root",
				importRef(ref("wasi", "io", "poll", "0.2.0")),
				importRef(ref("wasi", "clocks", "monotonic-clock", "0.2.0")),
				importRef(ref("wasi", "io", "error", "0.2.0")), importRef(ref("wasi", "io", "streams", "0.2.0")),
				importRef(ref("wasi", "http", "types", "0.2.0")), importRef(ref("wasi", "random", "random", "0.2.0")),
				importRef(ref("wasi", "clocks", "wall-clock", "0.2.0")),
				importRef(ref("wasi", "cli", "stdout", "0.2.0")), importRef(ref("wasi", "cli", "stderr", "0.2.0")),
				importRef(ref("wasi", "http", "outgoing-handler", "0.2.0")),
				exportRef(ref("wasi", "http", "incoming-handler", "0.2.0"))), wasiIoV020HttpServerClient(),
				wasiClocksV020(), wasiHttpV020HttpServerClient(), wasiRandomV020(), wasiCliV020());
	}

	private static WitDocument nogc() {
		return Wit.document(packageHeader("root", "component", null), world("root"));
	}

	private static WitDocument nogcPrint() {
		return Wit.document(packageHeader("root", "component", null),
				world("root", importRef(ref("wasi", "io", "error", "0.2.0")),
						importRef(ref("wasi", "io", "streams", "0.2.0")),
						importRef(ref("wasi", "cli", "stdout", "0.2.0"))),
				wasiIoV020NogcPrint(), wasiCliV020NogcPrint());
	}

	private static WitItem wasiCliV030() {
		return packageBlock("wasi", "cli", "0.3.0",
				iface("types", enumDef("error-code", "io", "illegal-byte-sequence", "pipe")),
				iface("stdout", use(localRef("types"), useName("error-code")),
						func("write-via-stream",
								funcType(future(result(null, named("error-code"))), param("data", stream(u8()))))),
				iface("stdin", use(localRef("types"), useName("error-code")),
						func("read-via-stream",
								funcType(tuple(stream(u8()), future(result(null, named("error-code"))))))),
				iface("environment", func("get-environment", funcType(list(tuple(string(), string()))))),
				iface("stderr", use(localRef("types"), useName("error-code")),
						func("write-via-stream",
								funcType(future(result(null, named("error-code"))), param("data", stream(u8()))))),
				iface("run", func("run", asyncFuncType(result()))));
	}

	private static WitItem wasiClocksV030() {
		return packageBlock("wasi", "clocks", "0.3.0",
				iface("system-clock", record("instant", field("seconds", s64()), field("nanoseconds", u32())),
						func("now", funcType(named("instant")))),
				iface("monotonic-clock", typeAlias("mark", u64()), func("now", funcType(named("mark")))));
	}

	private static WitItem wasiFilesystemV030() {
		return packageBlock("wasi", "filesystem", "0.3.0", iface("types", resource("descriptor",
				func("read-via-stream",
						funcType(tuple(stream(u8()), future(result(null, named("error-code")))),
								param("offset", named("filesize")))),
				func("append-via-stream",
						funcType(future(result(null, named("error-code"))), param("data", stream(u8())))),
				func("open-at",
						asyncFuncType(result(named("descriptor"), named("error-code")),
								param("path-flags", named("path-flags")), param("path", string()),
								param("open-flags", named("open-flags")), param("flags", named("descriptor-flags"))))),
				typeAlias("filesize", u64()),
				variant("error-code", vcase("access"), vcase("already"), vcase("bad-descriptor"), vcase("busy"),
						vcase("deadlock"), vcase("quota"), vcase("exist"), vcase("file-too-large"),
						vcase("illegal-byte-sequence"), vcase("in-progress"), vcase("interrupted"), vcase("invalid"),
						vcase("io"), vcase("is-directory"), vcase("loop"), vcase("too-many-links"),
						vcase("message-size"), vcase("name-too-long"), vcase("no-device"), vcase("no-entry"),
						vcase("no-lock"), vcase("insufficient-memory"), vcase("insufficient-space"),
						vcase("not-directory"), vcase("not-empty"), vcase("not-recoverable"), vcase("unsupported"),
						vcase("no-tty"), vcase("no-such-device"), vcase("overflow"), vcase("not-permitted"),
						vcase("pipe"), vcase("read-only"), vcase("invalid-seek"), vcase("text-file-busy"),
						vcase("cross-device"), vcase("other", option(string()))),
				flags("path-flags", "symlink-follow"),
				flags("open-flags", "create", "directory", "exclusive", "truncate"),
				flags("descriptor-flags", "read", "write", "file-integrity-sync", "data-integrity-sync",
						"requested-write-sync", "mutate-directory")),
				iface("preopens", use(localRef("types"), useName("descriptor")),
						func("get-directories", funcType(list(tuple(named("descriptor"), string()))))));
	}

	private static WitItem wasiRandomV030() {
		return packageBlock("wasi", "random", "0.3.0", iface("random", func("get-random-u64", funcType(u64()))));
	}

	private static WitItem wasiIoV020() {
		return packageBlock("wasi", "io", "0.2.0", iface("poll", resource("pollable", func("block", funcType()))),
				iface("error", resource("error")),
				iface("streams", use(localRef("error"), useName("error")),
						resource("output-stream",
								func("blocking-write-and-flush",
										funcType(result(null, named("stream-error")), param("contents", list(u8()))))),
						variant("stream-error", vcase("last-operation-failed", named("error")), vcase("closed")),
						resource("input-stream", func("blocking-read",
								funcType(result(list(u8()), named("stream-error")), param("len", u64()))))));
	}

	private static WitItem wasiHttpV020() {
		return packageBlock("wasi", "http", "0.2.0",
				iface("types", use(ref("wasi", "io", "streams", "0.2.0"), useName("output-stream")),
						use(ref("wasi", "io", "poll", "0.2.0"), useName("pollable")),
						use(ref("wasi", "io", "streams", "0.2.0"), useName("input-stream")),
						resource("fields", constructor(),
								func("append",
										funcType(result(null, named("header-error")), param("name", named("field-key")),
												param("value", named("field-value")))),
								func("entries", funcType(list(tuple(named("field-key"), named("field-value")))))),
						typeAlias("field-key", string()), typeAlias("field-value", list(u8())),
						variant("header-error", vcase("invalid-syntax"), vcase("forbidden"), vcase("immutable")),
						typeAlias("headers", named("fields")),
						resource("outgoing-request", constructor(param("headers", named("headers"))),
								func("body", funcType(result(named("outgoing-body")))),
								func("set-method", funcType(result(), param("method", named("method")))),
								func("set-path-with-query",
										funcType(result(), param("path-with-query", option(string())))),
								func("set-scheme", funcType(result(), param("scheme", option(named("scheme"))))),
								func("set-authority", funcType(result(), param("authority", option(string()))))),
						variant("method", vcase("get"), vcase("head"), vcase("post"), vcase("put"), vcase("delete"),
								vcase("connect"), vcase("options"), vcase("trace"), vcase("patch"),
								vcase("other", string())),
						variant("scheme", vcase("HTTP"), vcase("HTTPS"), vcase("other", string())),
						resource("outgoing-body", func("write", funcType(result(named("output-stream")))), staticFunc(
								"finish",
								funcType(result(null, named("error-code")), param("this", named("outgoing-body")),
										param("trailers", option(named("trailers")))))),
						typeAlias("trailers", named("fields")),
						record("DNS-error-payload", field("rcode", option(string())),
								field("info-code", option(u16()))),
						record("TLS-alert-received-payload", field("alert-id", option(u8())),
								field("alert-message", option(string()))),
						record("field-size-payload", field("field-name", option(string())),
								field("field-size", option(u32()))),
						variant("error-code", vcase("DNS-timeout"), vcase("DNS-error", named("DNS-error-payload")),
								vcase("destination-not-found"), vcase("destination-unavailable"),
								vcase("destination-IP-prohibited"), vcase("destination-IP-unroutable"),
								vcase("connection-refused"), vcase("connection-terminated"),
								vcase("connection-timeout"), vcase("connection-read-timeout"),
								vcase("connection-write-timeout"), vcase("connection-limit-reached"),
								vcase("TLS-protocol-error"), vcase("TLS-certificate-error"),
								vcase("TLS-alert-received", named("TLS-alert-received-payload")),
								vcase("HTTP-request-denied"), vcase("HTTP-request-length-required"),
								vcase("HTTP-request-body-size", option(u64())), vcase("HTTP-request-method-invalid"),
								vcase("HTTP-request-URI-invalid"), vcase("HTTP-request-URI-too-long"),
								vcase("HTTP-request-header-section-size", option(u32())),
								vcase("HTTP-request-header-size", option(named("field-size-payload"))),
								vcase("HTTP-request-trailer-section-size", option(u32())),
								vcase("HTTP-request-trailer-size", named("field-size-payload")),
								vcase("HTTP-response-incomplete"),
								vcase("HTTP-response-header-section-size", option(u32())),
								vcase("HTTP-response-header-size", named("field-size-payload")),
								vcase("HTTP-response-body-size", option(u64())),
								vcase("HTTP-response-trailer-section-size", option(u32())),
								vcase("HTTP-response-trailer-size", named("field-size-payload")),
								vcase("HTTP-response-transfer-coding", option(string())),
								vcase("HTTP-response-content-coding", option(string())), vcase("HTTP-response-timeout"),
								vcase("HTTP-upgrade-failed"), vcase("HTTP-protocol-error"), vcase("loop-detected"),
								vcase("configuration-error"), vcase("internal-error", option(string()))),
						resource("future-incoming-response", func("subscribe", funcType(named("pollable"))), func("get",
								funcType(option(result(result(named("incoming-response"), named("error-code"))))))),
						resource("incoming-response", func("status", funcType(named("status-code"))),
								func("headers", funcType(named("headers"))),
								func("consume", funcType(result(named("incoming-body"))))),
						typeAlias("status-code", u16()),
						resource("incoming-body", func("stream", funcType(result(named("input-stream"))))),
						resource("request-options")),
				iface("outgoing-handler",
						use(localRef("types"), useName("outgoing-request"), useName("request-options"),
								useName("future-incoming-response"), useName("error-code")),
						func("handle",
								funcType(result(named("future-incoming-response"), named("error-code")),
										param("request", named("outgoing-request")),
										param("options", option(named("request-options")))))));
	}

	private static WitItem wasiSocketsV030() {
		return packageBlock("wasi", "sockets", "0.3.0", iface("types",
				resource("tcp-socket",
						staticFunc(
								"create",
								funcType(result(named("tcp-socket"), named("error-code")),
										param("address-family", named("ip-address-family")))),
						func("bind",
								funcType(result(null, named("error-code")),
										param("local-address", named("ip-socket-address")))),
						func("connect",
								asyncFuncType(result(null, named("error-code")),
										param("remote-address", named("ip-socket-address")))),
						func("listen", funcType(result(stream(named("tcp-socket")), named("error-code")))),
						func("send", funcType(future(result(null, named("error-code"))), param("data", stream(u8())))),
						func("receive", funcType(tuple(stream(u8()), future(result(null, named("error-code")))))),
						func("get-local-address", funcType(result(named("ip-socket-address"), named("error-code"))))),
				enumDef("ip-address-family", "ipv4", "ipv6"),
				variant("error-code", vcase("access-denied"), vcase("not-supported"), vcase("invalid-argument"),
						vcase("out-of-memory"), vcase("timeout"), vcase("invalid-state"), vcase("address-not-bindable"),
						vcase("address-in-use"), vcase("remote-unreachable"), vcase("connection-refused"),
						vcase("connection-broken"), vcase("connection-reset"), vcase("connection-aborted"),
						vcase("datagram-too-large"), vcase("other", option(string()))),
				typeAlias("ipv4-address", tuple(u8(), u8(), u8(), u8())),
				record("ipv4-socket-address", field("port", u16()), field("address", named("ipv4-address"))),
				typeAlias("ipv6-address", tuple(u16(), u16(), u16(), u16(), u16(), u16(), u16(), u16())),
				record("ipv6-socket-address", field("port", u16()), field("flow-info", u32()),
						field("address", named("ipv6-address")), field("scope-id", u32())),
				variant("ip-socket-address", vcase("ipv4", named("ipv4-socket-address")),
						vcase("ipv6", named("ipv6-socket-address")))));
	}

	private static WitItem wasiClocksV020() {
		return packageBlock("wasi", "clocks", "0.2.0",
				iface("monotonic-clock", typeAlias("instant", u64()), func("now", funcType(named("instant")))),
				iface("wall-clock", record("datetime", field("seconds", u64()), field("nanoseconds", u32())),
						func("now", funcType(named("datetime")))));
	}

	private static WitItem wasiIoV020HttpServer() {
		return packageBlock("wasi", "io", "0.2.0", iface("error", resource("error")),
				iface("streams", use(localRef("error"), useName("error")),
						resource("input-stream",
								func("blocking-read",
										funcType(result(list(u8()), named("stream-error")), param("len", u64())))),
						resource("output-stream",
								func("blocking-write-and-flush",
										funcType(result(null, named("stream-error")), param("contents", list(u8()))))),
						variant("stream-error", vcase("last-operation-failed", named("error")), vcase("closed"))));
	}

	private static WitItem wasiHttpV020HttpServer() {
		return packageBlock("wasi", "http", "0.2.0", iface("types",
				use(ref("wasi", "io", "streams", "0.2.0"), useName("input-stream"), useName("output-stream")),
				resource("incoming-request", func("method", funcType(named("method"))),
						func("path-with-query", funcType(option(string()))),
						func("consume", funcType(result(named("incoming-body"))))),
				variant("method", vcase("get"), vcase("head"), vcase("post"), vcase("put"), vcase("delete"),
						vcase("connect"), vcase("options"), vcase("trace"), vcase("patch"), vcase("other", string())),
				resource("incoming-body", func("stream", funcType(result(named("input-stream"))))),
				resource("fields", constructor()), typeAlias("headers", named("fields")),
				resource("outgoing-response", constructor(param("headers", named("headers"))),
						func("set-status-code", funcType(result(), param("status-code", named("status-code")))),
						func("body", funcType(result(named("outgoing-body"))))),
				typeAlias("status-code", u16()),
				resource("outgoing-body", func("write", funcType(result(named("output-stream")))),
						staticFunc("finish",
								funcType(result(null, named("error-code")), param("this", named("outgoing-body")),
										param("trailers", option(named("trailers")))))),
				typeAlias("trailers", named("fields")),
				record("DNS-error-payload", field("rcode", option(string())), field("info-code", option(u16()))),
				record("TLS-alert-received-payload", field("alert-id", option(u8())),
						field("alert-message", option(string()))),
				record("field-size-payload", field("field-name", option(string())), field("field-size", option(u32()))),
				variant("error-code", vcase("DNS-timeout"), vcase("DNS-error", named("DNS-error-payload")),
						vcase("destination-not-found"), vcase("destination-unavailable"),
						vcase("destination-IP-prohibited"), vcase("destination-IP-unroutable"),
						vcase("connection-refused"), vcase("connection-terminated"), vcase("connection-timeout"),
						vcase("connection-read-timeout"), vcase("connection-write-timeout"),
						vcase("connection-limit-reached"), vcase("TLS-protocol-error"), vcase("TLS-certificate-error"),
						vcase("TLS-alert-received", named("TLS-alert-received-payload")), vcase("HTTP-request-denied"),
						vcase("HTTP-request-length-required"), vcase("HTTP-request-body-size", option(u64())),
						vcase("HTTP-request-method-invalid"), vcase("HTTP-request-URI-invalid"),
						vcase("HTTP-request-URI-too-long"), vcase("HTTP-request-header-section-size", option(u32())),
						vcase("HTTP-request-header-size", option(named("field-size-payload"))),
						vcase("HTTP-request-trailer-section-size", option(u32())),
						vcase("HTTP-request-trailer-size", named("field-size-payload")),
						vcase("HTTP-response-incomplete"), vcase("HTTP-response-header-section-size", option(u32())),
						vcase("HTTP-response-header-size", named("field-size-payload")),
						vcase("HTTP-response-body-size", option(u64())),
						vcase("HTTP-response-trailer-section-size", option(u32())),
						vcase("HTTP-response-trailer-size", named("field-size-payload")),
						vcase("HTTP-response-transfer-coding", option(string())),
						vcase("HTTP-response-content-coding", option(string())), vcase("HTTP-response-timeout"),
						vcase("HTTP-upgrade-failed"), vcase("HTTP-protocol-error"), vcase("loop-detected"),
						vcase("configuration-error"), vcase("internal-error", option(string()))),
				resource("response-outparam",
						staticFunc("set",
								funcType(param("param", named("response-outparam")),
										param("response", result(named("outgoing-response"), named("error-code"))))))),
				iface("incoming-handler",
						use(localRef("types"), useName("incoming-request"), useName("response-outparam")),
						func("handle", funcType(param("request", named("incoming-request")),
								param("response-out", named("response-outparam"))))));
	}

	private static WitItem wasiRandomV020() {
		return packageBlock("wasi", "random", "0.2.0", iface("random", func("get-random-u64", funcType(u64()))));
	}

	private static WitItem wasiCliV020() {
		return packageBlock("wasi", "cli", "0.2.0",
				iface("stdout", use(ref("wasi", "io", "streams", "0.2.0"), useName("output-stream")),
						func("get-stdout", funcType(named("output-stream")))),
				iface("stderr", use(ref("wasi", "io", "streams", "0.2.0"), useName("output-stream")),
						func("get-stderr", funcType(named("output-stream")))));
	}

	private static WitItem wasiIoV020HttpServerClient() {
		return packageBlock("wasi", "io", "0.2.0", iface("poll", resource("pollable", func("block", funcType()))),
				iface("error", resource("error")),
				iface("streams", use(localRef("error"), useName("error")),
						resource("input-stream",
								func("blocking-read",
										funcType(result(list(u8()), named("stream-error")), param("len", u64())))),
						resource("output-stream",
								func("blocking-write-and-flush",
										funcType(result(null, named("stream-error")), param("contents", list(u8()))))),
						variant("stream-error", vcase("last-operation-failed", named("error")), vcase("closed"))));
	}

	private static WitItem wasiHttpV020HttpServerClient() {
		return packageBlock("wasi", "http", "0.2.0",
				iface("types",
						use(ref("wasi", "io", "streams", "0.2.0"), useName("input-stream"), useName("output-stream")),
						use(ref("wasi", "io", "poll", "0.2.0"), useName("pollable")),
						resource("incoming-request", func("method", funcType(named("method"))),
								func("path-with-query", funcType(option(string()))),
								func("consume", funcType(result(named("incoming-body"))))),
						variant("method", vcase("get"), vcase("head"), vcase("post"), vcase("put"), vcase("delete"),
								vcase("connect"), vcase("options"), vcase("trace"), vcase("patch"),
								vcase("other", string())),
						resource("incoming-body", func("stream", funcType(result(named("input-stream"))))),
						resource("fields", constructor(),
								func("append",
										funcType(result(null, named("header-error")), param("name", named("field-key")),
												param("value", named("field-value")))),
								func("entries", funcType(list(tuple(named("field-key"), named("field-value")))))),
						typeAlias("headers", named("fields")),
						resource("outgoing-response", constructor(param("headers", named("headers"))),
								func("set-status-code", funcType(result(), param("status-code", named("status-code")))),
								func("body", funcType(result(named("outgoing-body"))))),
						typeAlias("status-code", u16()),
						resource("outgoing-body", func("write", funcType(result(named("output-stream")))), staticFunc(
								"finish",
								funcType(result(null, named("error-code")), param("this", named("outgoing-body")),
										param("trailers", option(named("trailers")))))),
						typeAlias("trailers", named("fields")), record(
								"DNS-error-payload", field("rcode", option(string())),
								field("info-code", option(u16()))),
						record("TLS-alert-received-payload", field("alert-id", option(u8())),
								field("alert-message", option(string()))),
						record("field-size-payload", field("field-name", option(string())),
								field("field-size", option(u32()))),
						variant("error-code", vcase("DNS-timeout"), vcase("DNS-error", named("DNS-error-payload")),
								vcase("destination-not-found"), vcase("destination-unavailable"),
								vcase("destination-IP-prohibited"), vcase("destination-IP-unroutable"),
								vcase("connection-refused"), vcase("connection-terminated"),
								vcase("connection-timeout"), vcase("connection-read-timeout"),
								vcase("connection-write-timeout"), vcase("connection-limit-reached"),
								vcase("TLS-protocol-error"), vcase("TLS-certificate-error"),
								vcase("TLS-alert-received", named("TLS-alert-received-payload")),
								vcase("HTTP-request-denied"), vcase("HTTP-request-length-required"),
								vcase("HTTP-request-body-size", option(u64())), vcase("HTTP-request-method-invalid"),
								vcase("HTTP-request-URI-invalid"), vcase("HTTP-request-URI-too-long"),
								vcase("HTTP-request-header-section-size", option(u32())),
								vcase("HTTP-request-header-size", option(named("field-size-payload"))),
								vcase("HTTP-request-trailer-section-size", option(u32())),
								vcase("HTTP-request-trailer-size", named("field-size-payload")),
								vcase("HTTP-response-incomplete"),
								vcase("HTTP-response-header-section-size", option(u32())),
								vcase("HTTP-response-header-size", named("field-size-payload")),
								vcase("HTTP-response-body-size", option(u64())),
								vcase("HTTP-response-trailer-section-size", option(u32())),
								vcase("HTTP-response-trailer-size", named("field-size-payload")),
								vcase("HTTP-response-transfer-coding", option(string())),
								vcase("HTTP-response-content-coding", option(string())), vcase("HTTP-response-timeout"),
								vcase("HTTP-upgrade-failed"), vcase("HTTP-protocol-error"), vcase("loop-detected"),
								vcase("configuration-error"), vcase("internal-error", option(string()))),
						resource("response-outparam", staticFunc("set",
								funcType(param("param", named("response-outparam")),
										param("response", result(named("outgoing-response"), named("error-code")))))),
						typeAlias("field-key", string()), typeAlias("field-value", list(u8())),
						variant("header-error", vcase("invalid-syntax"), vcase("forbidden"), vcase("immutable")),
						resource("outgoing-request", constructor(param("headers", named("headers"))),
								func("body", funcType(result(named("outgoing-body")))),
								func("set-method", funcType(result(), param("method", named("method")))),
								func("set-path-with-query",
										funcType(result(), param("path-with-query", option(string())))),
								func("set-scheme", funcType(result(), param("scheme", option(named("scheme"))))),
								func("set-authority", funcType(result(), param("authority", option(string()))))),
						variant("scheme", vcase("HTTP"), vcase("HTTPS"), vcase("other", string())),
						resource("future-incoming-response", func("subscribe", funcType(named("pollable"))), func("get",
								funcType(option(result(result(named("incoming-response"), named("error-code"))))))),
						resource("incoming-response", func("status", funcType(named("status-code"))),
								func("headers", funcType(named("headers"))),
								func("consume", funcType(result(named("incoming-body"))))),
						resource("request-options")),
				iface("outgoing-handler",
						use(localRef("types"), useName("outgoing-request"), useName("request-options"),
								useName("future-incoming-response"), useName("error-code")),
						func("handle",
								funcType(result(named("future-incoming-response"), named("error-code")),
										param("request", named("outgoing-request")),
										param("options", option(named("request-options")))))),
				iface("incoming-handler",
						use(localRef("types"), useName("incoming-request"), useName("response-outparam")),
						func("handle", funcType(param("request", named("incoming-request")),
								param("response-out", named("response-outparam"))))));
	}

	private static WitItem wasiIoV020NogcPrint() {
		return packageBlock("wasi", "io", "0.2.0", iface("error", resource("error")),
				iface("streams", use(localRef("error"), useName("error")),
						resource("output-stream",
								func("blocking-write-and-flush",
										funcType(result(null, named("stream-error")), param("contents", list(u8()))))),
						variant("stream-error", vcase("last-operation-failed", named("error")), vcase("closed"))));
	}

	private static WitItem wasiCliV020NogcPrint() {
		return packageBlock("wasi", "cli", "0.2.0",
				iface("stdout", use(ref("wasi", "io", "streams", "0.2.0"), useName("output-stream")),
						func("get-stdout", funcType(named("output-stream")))));
	}

}
