package am.ik.rontolisp.codegen.wasm;

import am.ik.wit.Wit;
import am.ik.wit.WitDocument;
import am.ik.wit.WitItem;

import static am.ik.wit.Wit.*;

/**
 * The fixed WIT worlds of the {@code --component} blob variants -- the world's WASI
 * imports, the fixed {@code wasi:cli/run} / {@code wasi:http/incoming-handler} export and
 * the referenced (reachability-pruned) package definitions -- as document models for
 * {@link WitEmitter}. Byte-equality of the canonical print with
 * {@code wasm-tools component wit} is pinned per variant by
 * {@code WasiWitDefinitionsTest} against the fixtures under
 * {@code src/test/resources/.../component/wit/}.
 *
 * <p>
 * GENERATED by {@code WasiWitDefinitionsGenerator} from those fixtures -- after changing
 * a blob's import surface, re-run {@code src/wasm-component/regen-wit.sh} and the
 * generator instead of editing this file (see {@code src/wasm-component/README.md}).
 */
final class WasiWitDefinitions {

	private WasiWitDefinitions() {
	}

	/**
	 * The fixed WIT document of a blob variant.
	 * @param variant one of the {@code WitEmitter.VARIANT_*} names
	 * @return the document (package header, world, package definitions)
	 */
	static WitDocument document(String variant) {
		return switch (variant) {
			case WitEmitter.VARIANT_BASE -> base();
			case WitEmitter.VARIANT_HTTP_SERVER -> httpServer();
			case WitEmitter.VARIANT_NOGC -> nogc();
			case WitEmitter.VARIANT_NOGC_PRINT -> nogcPrint();
			default -> throw new IllegalStateException("Missing WIT definition for variant: " + variant);
		};
	}

	private static WitDocument base() {
		return Wit.document(packageHeader("root", "component", null), world("root",
				importRef(ref("wasi", "cli", "types", "0.3.0")), importRef(ref("wasi", "cli", "stdout", "0.3.0")),
				importRef(ref("wasi", "cli", "stdin", "0.3.0")), importRef(ref("wasi", "cli", "environment", "0.3.0")),
				importRef(ref("wasi", "clocks", "types", "0.3.0")),
				importRef(ref("wasi", "clocks", "system-clock", "0.3.0")),
				importRef(ref("wasi", "clocks", "monotonic-clock", "0.3.0")),
				importRef(ref("wasi", "filesystem", "types", "0.3.0")),
				importRef(ref("wasi", "filesystem", "preopens", "0.3.0")),
				importRef(ref("wasi", "random", "random", "0.3.0")), importRef(ref("wasi", "cli", "stderr", "0.3.0")),
				exportRef(ref("wasi", "cli", "run", "0.3.0"))), wasiCliV030(), wasiClocksV030(), wasiFilesystemV030(),
				wasiRandomV030());
	}

	private static WitDocument httpServer() {
		return Wit.document(packageHeader("root", "component", null), world("root",
				importRef(ref("wasi", "clocks", "types", "0.3.0")), importRef(ref("wasi", "http", "types", "0.3.0")),
				importRef(ref("wasi", "http", "client", "0.3.0")), importRef(ref("wasi", "random", "random", "0.3.0")),
				importRef(ref("wasi", "clocks", "system-clock", "0.3.0")),
				importRef(ref("wasi", "clocks", "monotonic-clock", "0.3.0")),
				importRef(ref("wasi", "cli", "types", "0.3.0")), importRef(ref("wasi", "cli", "stdout", "0.3.0")),
				importRef(ref("wasi", "cli", "stderr", "0.3.0")), exportRef(ref("wasi", "http", "handler", "0.3.0"))),
				wasiClocksV030(), wasiHttpV030(), wasiRandomV030(), wasiCliV030HttpServer());
	}

	private static WitDocument nogc() {
		return Wit.document(packageHeader("root", "component", null), world("root"));
	}

	private static WitDocument nogcPrint() {
		return Wit.document(packageHeader("root", "component", null), world("root",
				importRef(ref("wasi", "cli", "types", "0.3.0")), importRef(ref("wasi", "cli", "stdout", "0.3.0"))),
				wasiCliV030NogcPrint());
	}

	private static WitItem wasiCliV030() {
		return packageBlock("wasi", "cli", "0.3.0",
				iface("types", enumDef("error-code", "io", "illegal-byte-sequence", "pipe")),
				iface("stdout", use(localRef("types"), useName("error-code")),
						func("write-via-stream",
								funcType(future(result(null, named("error-code"))), param("data", stream(u8()))))),
				iface("stdin", use(localRef("types"), useName("error-code")),
						func("read-via-stream",
								funcType(tuple(stream(u8()), future(result(null, named("error-code"))))))),
				iface("environment", func("get-environment", funcType(list(tuple(string(), string()))))),
				iface("stderr", use(localRef("types"), useName("error-code")),
						func("write-via-stream",
								funcType(future(result(null, named("error-code"))), param("data", stream(u8()))))),
				iface("run", func("run", asyncFuncType(result()))));
	}

	private static WitItem wasiClocksV030() {
		return packageBlock("wasi", "clocks", "0.3.0", iface("types", typeAlias("duration", u64())),
				iface("system-clock", record("instant", field("seconds", s64()), field("nanoseconds", u32())),
						func("now", funcType(named("instant")))),
				iface("monotonic-clock", use(localRef("types"), useName("duration")), typeAlias("mark", u64()),
						func("now", funcType(named("mark"))),
						func("wait-for", asyncFuncType(param("how-long", named("duration"))))));
	}

	private static WitItem wasiFilesystemV030() {
		return packageBlock("wasi", "filesystem", "0.3.0", iface("types", resource("descriptor",
				func("read-via-stream",
						funcType(tuple(stream(u8()), future(result(null, named("error-code")))),
								param("offset", named("filesize")))),
				func("append-via-stream",
						funcType(future(result(null, named("error-code"))), param("data", stream(u8())))),
				func("read-directory",
						funcType(tuple(stream(named("directory-entry")), future(result(null, named("error-code")))))),
				func("open-at",
						asyncFuncType(result(named("descriptor"), named("error-code")),
								param("path-flags", named("path-flags")), param("path", string()),
								param("open-flags", named("open-flags")), param("flags", named("descriptor-flags"))))),
				typeAlias("filesize", u64()),
				variant("error-code", vcase("access"), vcase("already"), vcase("bad-descriptor"), vcase("busy"),
						vcase("deadlock"), vcase("quota"), vcase("exist"), vcase("file-too-large"),
						vcase("illegal-byte-sequence"), vcase("in-progress"), vcase("interrupted"), vcase("invalid"),
						vcase("io"), vcase("is-directory"), vcase("loop"), vcase("too-many-links"),
						vcase("message-size"), vcase("name-too-long"), vcase("no-device"), vcase("no-entry"),
						vcase("no-lock"), vcase("insufficient-memory"), vcase("insufficient-space"),
						vcase("not-directory"), vcase("not-empty"), vcase("not-recoverable"), vcase("unsupported"),
						vcase("no-tty"), vcase("no-such-device"), vcase("overflow"), vcase("not-permitted"),
						vcase("pipe"), vcase("read-only"), vcase("invalid-seek"), vcase("text-file-busy"),
						vcase("cross-device"), vcase("other", option(string()))),
				flags("path-flags", "symlink-follow"),
				flags("open-flags", "create", "directory", "exclusive", "truncate"),
				flags("descriptor-flags", "read", "write", "file-integrity-sync", "data-integrity-sync",
						"requested-write-sync", "mutate-directory"),
				variant("descriptor-type", vcase("block-device"), vcase("character-device"), vcase("directory"),
						vcase("fifo"), vcase("symbolic-link"), vcase("regular-file"), vcase("socket"),
						vcase("other", option(string()))),
				record("directory-entry", field("type", named("descriptor-type")), field("name", string()))),
				iface("preopens", use(localRef("types"), useName("descriptor")),
						func("get-directories", funcType(list(tuple(named("descriptor"), string()))))));
	}

	private static WitItem wasiRandomV030() {
		return packageBlock("wasi", "random", "0.3.0", iface("random", func("get-random-u64", funcType(u64()))));
	}

	private static WitItem wasiHttpV030() {
		return packageBlock("wasi", "http", "0.3.0",
				iface("types",
						resource("fields", constructor(),
								func("append", funcType(result(null, named("header-error")),
										param("name", named("field-name")), param("value", named("field-value")))),
								func("copy-all", funcType(list(tuple(named("field-name"), named("field-value")))))),
						typeAlias("field-name", string()), typeAlias("field-value", list(u8())),
						variant("header-error", vcase("invalid-syntax"), vcase("forbidden"), vcase("immutable"),
								vcase("size-exceeded"), vcase("other", option(string()))),
						resource("request",
								staticFunc("new",
										funcType(tuple(named("request"), future(result(null, named("error-code")))),
												param("headers", named("headers")),
												param("contents", option(stream(u8()))),
												param("trailers",
														future(result(option(named("trailers")), named("error-code")))),
												param("options", option(named("request-options"))))),
								func("get-method", funcType(named("method"))),
								func("set-method", funcType(result(), param("method", named("method")))),
								func("get-path-with-query", funcType(option(string()))),
								func("set-path-with-query",
										funcType(result(), param("path-with-query", option(string())))),
								func("set-scheme", funcType(result(), param("scheme", option(named("scheme"))))),
								func("set-authority", funcType(result(), param("authority", option(string())))),
								func("get-headers", funcType(
										named("headers"))),
								staticFunc("consume-body",
										funcType(
												tuple(stream(u8()),
														future(result(option(named("trailers")), named("error-code")))),
												param("this", named("request")),
												param("res", future(result(null, named("error-code"))))))),
						typeAlias("headers", named("fields")), typeAlias("trailers", named("fields")),
						record("DNS-error-payload", field("rcode", option(string())), field("info-code",
								option(u16()))),
						record("TLS-alert-received-payload", field("alert-id", option(u8())),
								field("alert-message", option(string()))),
						record("field-size-payload", field("field-name", option(string())),
								field("field-size", option(u32()))),
						variant("error-code", vcase("DNS-timeout"), vcase("DNS-error", named("DNS-error-payload")),
								vcase("destination-not-found"), vcase("destination-unavailable"),
								vcase("destination-IP-prohibited"), vcase("destination-IP-unroutable"),
								vcase("connection-refused"), vcase("connection-terminated"),
								vcase("connection-timeout"), vcase("connection-read-timeout"),
								vcase("connection-write-timeout"), vcase("connection-limit-reached"),
								vcase("TLS-protocol-error"), vcase("TLS-certificate-error"),
								vcase("TLS-alert-received", named("TLS-alert-received-payload")),
								vcase("HTTP-request-denied"), vcase("HTTP-request-length-required"),
								vcase("HTTP-request-body-size", option(u64())), vcase("HTTP-request-method-invalid"),
								vcase("HTTP-request-URI-invalid"), vcase("HTTP-request-URI-too-long"),
								vcase("HTTP-request-header-section-size", option(u32())),
								vcase("HTTP-request-header-size", option(named("field-size-payload"))),
								vcase("HTTP-request-trailer-section-size", option(u32())),
								vcase("HTTP-request-trailer-size", named("field-size-payload")),
								vcase("HTTP-response-incomplete"),
								vcase("HTTP-response-header-section-size", option(u32())),
								vcase("HTTP-response-header-size", named("field-size-payload")),
								vcase("HTTP-response-body-size", option(u64())),
								vcase("HTTP-response-trailer-section-size", option(u32())),
								vcase("HTTP-response-trailer-size", named("field-size-payload")),
								vcase("HTTP-response-transfer-coding", option(string())),
								vcase("HTTP-response-content-coding", option(string())), vcase("HTTP-response-timeout"),
								vcase("HTTP-upgrade-failed"), vcase(
										"HTTP-protocol-error"),
								vcase("loop-detected"), vcase("configuration-error"),
								vcase("internal-error", option(string()))),
						resource("request-options"),
						variant("method", vcase("get"), vcase("head"), vcase("post"), vcase("put"), vcase("delete"),
								vcase("connect"), vcase("options"), vcase("trace"), vcase("patch"),
								vcase("other", string())),
						variant("scheme", vcase("HTTP"), vcase("HTTPS"), vcase("other", string())),
						resource("response", staticFunc("new",
								funcType(tuple(named("response"), future(result(null, named("error-code")))),
										param("headers", named("headers")), param("contents", option(stream(u8()))),
										param("trailers",
												future(result(option(named("trailers")), named("error-code")))))),
								func("get-status-code", funcType(named("status-code"))),
								func("set-status-code", funcType(result(), param("status-code", named("status-code")))),
								func("get-headers", funcType(
										named("headers"))),
								staticFunc("consume-body",
										funcType(
												tuple(stream(u8()),
														future(result(option(named("trailers")), named("error-code")))),
												param("this", named("response")),
												param("res", future(result(null, named("error-code"))))))),
						typeAlias("status-code", u16())),
				iface("client", use(localRef("types"), useName("request"), useName("response"), useName("error-code")),
						func("send",
								asyncFuncType(result(named("response"), named("error-code")),
										param("request", named("request"))))),
				iface("handler", use(localRef("types"), useName("request"), useName("response"), useName("error-code")),
						func("handle", asyncFuncType(result(named("response"), named("error-code")),
								param("request", named("request"))))));
	}

	private static WitItem wasiCliV030HttpServer() {
		return packageBlock("wasi", "cli", "0.3.0",
				iface("types", enumDef("error-code", "io", "illegal-byte-sequence", "pipe")),
				iface("stdout", use(localRef("types"), useName("error-code")),
						func("write-via-stream",
								funcType(future(result(null, named("error-code"))), param("data", stream(u8()))))),
				iface("stderr", use(localRef("types"), useName("error-code")), func("write-via-stream",
						funcType(future(result(null, named("error-code"))), param("data", stream(u8()))))));
	}

	private static WitItem wasiCliV030NogcPrint() {
		return packageBlock("wasi", "cli", "0.3.0",
				iface("types", enumDef("error-code", "io", "illegal-byte-sequence", "pipe")),
				iface("stdout", use(localRef("types"), useName("error-code")), func("write-via-stream",
						funcType(future(result(null, named("error-code"))), param("data", stream(u8()))))));
	}

}
