package am.ik.rontolisp;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Pins the native-image resource registration of the bundled Lisp/WIT/asd resources.
 *
 * <p>
 * A resource the interpreter reads off the classpath ({@code eval/*.lisp}, a
 * {@code .wit}, a replacement {@code .asd}) is embedded in the native binary only when
 * {@code resource-config.json} lists a pattern matching it. A missing entry is invisible
 * to {@code ./mvnw test} -- the JVM run reads the file straight from
 * {@code target/classes} -- and surfaces only as
 * {@code <name> is missing from the classpath} at run time on the native binary, which is
 * how {@code ironclad-slice.asd} shipped unusable there. Adding a bundled resource
 * without its entry now fails here instead.
 */
class NativeImageResourceConfigTest {

	private static final Path RESOURCE_ROOT = Path.of("src", "main", "resources");

	private static final Path CONFIG = RESOURCE_ROOT
		.resolve(Path.of("META-INF", "native-image", "am.ik.rontolisp", "rontolisp", "resource-config.json"));

	/** The bundled directories whose every file must be reachable from the binary. */
	private static final List<String> BUNDLED_DIRS = List.of("am/ik/rontolisp/eval", "am/ik/rontolisp/macro",
			"am/ik/rontolisp/codegen/wasm/component");

	@Test
	void everyBundledResourceIsRegistered() throws IOException {
		List<Pattern> patterns = configuredPatterns();
		List<String> unregistered = new ArrayList<>();
		for (String dir : BUNDLED_DIRS) {
			Path directory = RESOURCE_ROOT.resolve(dir);
			assertThat(directory).as("bundled resource directory %s exists", dir).isDirectory();
			try (Stream<Path> files = Files.list(directory)) {
				files.filter(Files::isRegularFile)
					// Markdown next to a bundled resource is provenance for the reader,
					// never read at run time, so it needs no entry.
					.filter(p -> !p.getFileName().toString().endsWith(".md"))
					.map(p -> dir + "/" + p.getFileName())
					.sorted()
					.forEach(resource -> {
						if (patterns.stream().noneMatch(p -> p.matcher(resource).matches())) {
							unregistered.add(resource);
						}
					});
			}
		}
		assertThat(unregistered)
			.as("bundled resources with no matching pattern in %s -- they load on the JVM but are absent from the "
					+ "native binary", CONFIG)
			.isEmpty();
	}

	// The "pattern" values of resources.includes, read with a regex so the core test tree
	// stays free of a JSON dependency (the file is generated by hand, one entry per
	// line).
	private static List<Pattern> configuredPatterns() throws IOException {
		Matcher matcher = Pattern.compile("\"pattern\"\\s*:\\s*\"((?:[^\"\\\\]|\\\\.)*)\"")
			.matcher(Files.readString(CONFIG, StandardCharsets.UTF_8));
		List<Pattern> patterns = new ArrayList<>();
		while (matcher.find()) {
			// JSON string escaping: \\ in the file is one backslash in the regex.
			patterns.add(Pattern.compile(matcher.group(1).replace("\\\\", "\\")));
		}
		assertThat(patterns).as("resource patterns declared in %s", CONFIG).isNotEmpty();
		return patterns;
	}

}
