//! The Rust emphasizer. It EXPORTS the `casing` interface -- `shout` uppercases
//! the text and adds an exclamation mark. The Lisp app calls it; nothing here
//! knows the caller is Lisp, only the WIT does.
//!
//! `mod bindings` is generated by cargo-component from ../wit (see Cargo.toml's
//! [package.metadata.component.target]); `cargo component build` regenerates it.

#[allow(warnings)]
mod bindings;

use bindings::exports::example::textkit::casing::Guest;

struct Component;

impl Guest for Component {
    fn shout(text: String) -> String {
        format!("{}!", text.to_uppercase())
    }
}

bindings::export!(Component with_types_in bindings);
