// GENERATED by rontolisp --emit-js-glue -- do not edit.
//
// The host half of this module's boundary, derived from the program's own
// declarations: one import-object entry per rontolisp:wasm-import, one entry
// point per rontolisp:wasm-export, and every piece of linear-memory plumbing
// between them -- the (ptr, len) pair a :string crosses as, the __ronto_alloc
// bracket around a call, and the read(2) cursor a :bytes result is pulled
// through.
//
// What a declaration cannot state is what a host function DOES, so that is the
// one thing this file asks for: `host` is a plain function per import, keyed by
// import module and field, taking and answering ordinary JavaScript values --
// never a (ptr, len) pair, and, where an entry answers `chunk` below, a
// Uint8Array or a string with null for the end of them.
//
//   import { instantiate, suspending } from "./worker.js";
//
//   const lisp = instantiate(module, {
//     env: {
//       fetch: (text) => text,
//       readResponseBody: () => chunk,
//       readRequestBody: () => chunk,
//       writeResponseBody: (chunk) => {},
//     },
//   });
//   await lisp.handleRequest(text);
//
// A host that suspends marks its own entries -- suspending(async (...) => ...)
// -- and every entry point above then answers a promise: the marked imports are
// wrapped in WebAssembly.Suspending, each entry point that can reach one is
// entered through WebAssembly.promising, and calls are serialised onto one
// promise chain, because a suspended module returns to the host's event loop
// and a re-entered export refuses with a trap rather than corrupting both
// calls. Host state that belongs to ONE such call is set inside that section:
//
//   await lisp.serially(async (entry) => { ...; return entry.handleRequest(...) });
//
// Regenerate it, never edit it: --emit-js-glue on the compile that wrote the
// .wasm beside it.

const encoder = new TextEncoder();
const decoder = new TextDecoder();

const SUSPENDING = Symbol.for("rontolisp.suspending");

/**
 * Marks a host function as one that answers a promise, so the wasm stack parks
 * until it settles (JSPI). The wrapper is not free -- an import answering
 * SYNCHRONOUSLY through one still returns to the event loop -- so mark only the
 * entries this host really implements asynchronously.
 *
 * @param {Function} fn the host function
 * @returns {object} the marked entry, to be passed as the import
 */
export function suspending(fn) {
  return { [SUSPENDING]: fn };
}

/**
 * Instantiates the module against this host and returns its callable surface.
 *
 * @param {WebAssembly.Module} module the compiled module
 * @param {object} host one function per import, keyed by module and field
 * @returns {object} `exports`, plus one entry point per rontolisp:wasm-export
 */
export function instantiate(module, host = {}) {
  let exports;

  // Every view is built where it is used, never held: growing the module's
  // memory DETACHES the buffer behind every view taken before the growth, and a
  // suspending host resumes after growths it never saw.
  const readString = (ptr, len) =>
    decoder.decode(new Uint8Array(exports.memory.buffer, ptr, len));

  // Octets, COPIED: the module pops the staging behind the pointer the moment
  // the call returns, so a chunk not taken by then is one the host never gets.
  const readBytes = (ptr, len) =>
    new Uint8Array(exports.memory.buffer.slice(ptr, ptr + len));

  // Bytes the HOST hands over live in the module's own bump allocator, and
  // cross as the (ptr, len) pair every memory-typed value is.
  const write = (octets) => {
    const ptr = exports.__ronto_alloc(octets.length);
    new Uint8Array(exports.memory.buffer, ptr, octets.length).set(octets);
    return [ptr, octets.length];
  };
  const writeString = (value) => write(encoder.encode(String(value)));
  const octets = (chunk) =>
    typeof chunk === "string" ? encoder.encode(chunk) : chunk;

  // A host answers a value, or -- from an entry it marked suspending -- a promise
  // of one. Both shapes ride one expression, which is what lets this file drive a
  // synchronous host and a JSPI host without being written twice.
  const marked = new Set();
  const unmarked = (what) =>
    what +
    " answered a promise; wrap it in suspending() so the wasm stack parks" +
    " until it settles";
  const settle = (what, value, next) => {
    if (typeof value?.then === "function") {
      if (!marked.has(what)) {
        // Reported before it is thrown: this throw crosses back into wasm,
        // where a catch_all landing pad turns it into whatever the module
        // makes of a failed import.
        console.error(unmarked(what));
        throw new TypeError(unmarked(what));
      }
      return value.then(next);
    }
    return next(value);
  };

  // The entries the module really imports: --optimize shakes out an import the
  // program never calls, and a host should not have to know which survived.
  const linked = new Set(
    WebAssembly.Module.imports(module).map((i) => i.module + "." + i.name),
  );
  const bind = (moduleName, field, wrap) => {
    const key = moduleName + "." + field;
    const given = (host[moduleName] ?? {})[field];
    if (given == null) {
      if (!linked.has(key)) return undefined;
      throw new TypeError("host." + key + " is missing; this module imports it");
    }
    if (given[SUSPENDING] === undefined) {
      // An async function that was never marked is the one mistake worth
      // catching HERE, where the report is a plain stack and not whatever
      // the module makes of an import that threw.
      if (given.constructor?.name === "AsyncFunction") {
        throw new TypeError(unmarked("host." + key));
      }
      return wrap(key, given);
    }
    marked.add(key);
    return new WebAssembly.Suspending(wrap(key, given[SUSPENDING]));
  };

  // A :bytes RESULT is the read(2) shape: the MODULE owns the buffer and asks
  // for up to `cap` octets, so what a host answers is the next CHUNK and this
  // holds whatever did not fit. That remainder is the read side's only state,
  // and it is why a host supplies chunks rather than a reader -- which source
  // they come from (a ReadableStream, a Uint8Array) is all that is left to it.
  const readers = new Map();
  const reader = (what, source) => {
    let rest = null;
    let from = null;
    // A body the module did not drain belongs to the call that could have and
    // to no other, so every cursor is dropped at the next entry below -- and a
    // host whose SOURCE moves inside one call (a new upstream reply opened by
    // another import) drops this one itself with lisp.drop(key), because what
    // did not fit is held here and nothing else can see the source move.
    readers.set(what, () => {
      rest = null;
      from = null;
    });
    const drain = (ptr, cap) => {
      const n = Math.min(cap, rest.length);
      new Uint8Array(exports.memory.buffer, ptr, n).set(rest.subarray(0, n));
      rest = rest.subarray(n);
      return n;
    };
    // A read that FAILS answers a NEGATIVE count. Throwing would trap the
    // instance; the count is an error channel the module turns into a Lisp
    // condition where the octets are consumed, which is where every other
    // backend reports a transfer that broke mid-body.
    const failed = (error) => {
      console.error(what + " failed:", error);
      return -1;
    };
    return (args, ptr, cap) => {
      // The remainder belongs to the arguments that asked for it: a source
      // selected by argument must not be served the previous one's octets.
      const key = JSON.stringify(args);
      if (from !== key) {
        rest = null;
        from = key;
      }
      if (rest !== null && rest.length !== 0) return drain(ptr, cap);
      try {
        const answer = settle(what, source(...args), (chunk) => {
          rest = chunk == null ? new Uint8Array(0) : octets(chunk);
          return rest.length === 0 ? 0 : drain(ptr, cap);
        });
        return typeof answer?.then === "function"
          ? answer.then(undefined, failed)
          : answer;
      } catch (error) {
        return failed(error);
      }
    };
  };

  // What a read import left over, thrown away on demand. A host calls it when
  // the SOURCE behind that import moves under it INSIDE one call -- a new
  // upstream reply, say -- since the remainder is held above and nothing else
  // can see the source move. With no argument it drops every one of them.
  const drop = (key) =>
    key === undefined ? readers.forEach((f) => f()) : readers.get(key)?.();

  const imports = {
    env: {
      // (:string) -> :string
      fetch: bind("env", "fetch", (what, call) => {
        return (p0, p0Len) =>
          settle(what, call(readString(p0, p0Len)), writeString);
      }),
      // () -> :bytes
      readResponseBody: bind("env", "readResponseBody", (what, call) => {
        const read = reader(what, call);
        return (ptr, cap) => read([], ptr, cap);
      }),
      // () -> :bytes
      readRequestBody: bind("env", "readRequestBody", (what, call) => {
        const read = reader(what, call);
        return (ptr, cap) => read([], ptr, cap);
      }),
      // (:bytes) -> :void
      writeResponseBody: bind("env", "writeResponseBody", (what, call) => {
        return (p0, p0Len) =>
          settle(what, call(readBytes(p0, p0Len)), () => undefined);
      }),
    },
  };
  const instance = new WebAssembly.Instance(module, imports);
  exports = instance.exports;
  // Entropy, BEFORE the top level runs: a --no-wasi module imports none, so its
  // `random` starts from a constant and every instance would draw one sequence.
  // Seeding here also covers the draws a library makes while it LOADS. A Worker
  // forbids this in global scope, so instantiate on the first request.
  exports.__ronto_seed_random(
    new BigUint64Array(crypto.getRandomValues(new Uint8Array(8)).buffer)[0],
  );
  // And a clock, nanoseconds since the Unix epoch, for the same reason and
  // before the same line: until one is set the clock built-ins signal rather
  // than report 1970.
  exports.__ronto_set_time(BigInt(Date.now()) * 1000000n);
  exports._initialize();

  // The entry points a call chain can reach a suspending import from -- the
  // list the build prints -- entered through WebAssembly.promising exactly when
  // the host marked one. An unmarked host never pays for the promise.
  const suspends = marked.size !== 0;
  const entry$handleRequest = suspends
    ? WebAssembly.promising(exports["handle-request"])
    : exports["handle-request"];

  // One Lisp call at a time. A suspended call returns to the host's event loop,
  // and the module's own re-entry guard TRAPS a second entry rather than let two
  // calls share its allocator and its dynamic bindings -- so the queue is the
  // contract, not a nicety. `.then(work, work)` because one rejected call must
  // not wedge the chain behind it.
  let queue = Promise.resolve();
  const queued = (work) => {
    const done = queue.then(work, work);
    queue = done.then(
      () => {},
      () => {},
    );
    return done;
  };
  // A bare entry point only needs the queue when a host marked something: a
  // synchronous call cannot be interleaved, and paying a promise for it would
  // make every host asynchronous. `serially` below always takes it, because
  // the work it runs awaits and a second request WOULD land inside it.
  const serialised = (work) => (suspends ? queued(work) : work());

  // One call into the module: stage the arguments, enter, decode the result out
  // of the scratch it sits in, and only THEN pop the arena that scratch is in.
  // A promising entry answers a promise, so the tail rides `then`; a synchronous
  // one runs the same expression inline. `run` is how the call reaches the
  // module -- through the queue, or straight through when it is already inside
  // the one call the queue admits.
  const call = (run, entry, stage, decode) => {
    const work = () => {
      readers.forEach((drop) => drop());
      // The module's clock moves only when the host moves it, so move it per
      // call. Not a workaround for a frozen clock -- a Worker's own Date.now()
      // is frozen for the duration of a request as a timing-attack mitigation,
      // so a value that changes once per call is what the platform has.
      exports.__ronto_set_time(BigInt(Date.now()) * 1000000n);
      const mark = exports.__ronto_alloc_mark();
      const done = (raw) => {
        const value = decode(raw);
        exports.__ronto_alloc_reset(mark);
        return value;
      };
      // A TRAP skips the pop above and leaves the module's state half-written
      // with it, so a host that keeps serving instantiates again rather than
      // calling back into this instance.
      const raw = entry(...stage());
      return typeof raw?.then === "function" ? raw.then(done) : done(raw);
    };
    return run(work);
  };

  /** `handle-request` -- (:string) -> :string */
  const make$handleRequest =
    (run) =>
    (p0) => {
      return call(
        run,
        entry$handleRequest,
        () => {
          const a0 = writeString(p0);
          return [a0[0], a0[1]];
        },
        ([ptr, len]) => readString(ptr, len),
      );
    };


  // Host state that belongs to ONE call -- what the module pulls DURING it,
  // and what the call leaves behind -- is set and read inside `work`, which
  // runs in the same critical section: a suspended call returns to the event
  // loop, so setting it beside the call instead would let the next request
  // move it under this one. The entry points `work` is handed enter the module
  // directly, because the queue they would take is the one they are in.
  const inside = {
    handleRequest: make$handleRequest((work) => work()),
  };
  const serially = (work) => queued(() => work(inside));

  return {
    exports,
    handleRequest: make$handleRequest(serialised),
    drop,
    serially,
  };
}
