// GENERATED by rontolisp --emit-js-glue -- do not edit.
//
// The host half of this module's boundary, derived from the program's own
// declarations: one import-object entry per rontolisp:wasm-import, one entry
// point per rontolisp:wasm-export, and every piece of linear-memory plumbing
// between them -- the (ptr, len) pair a :string crosses as, the __ronto_alloc
// bracket around a call, and the read(2) cursor a :bytes result is pulled
// through.
//
// What a declaration cannot state is what a host function DOES, so that is the
// one thing this file asks for: `host` is a plain function per import, keyed by
// import module and field, taking and answering ordinary JavaScript values --
// never a (ptr, len) pair, and, where an entry answers `chunk` below, a
// Uint8Array or a string with null for the end of them.
//
//   import { instantiate, suspending } from "./worker.js";
//
//   const lisp = instantiate(module, {
//     env: {
//       fetch: (text) => text,   // or leave it to defaultHost()
//       readResponseBody: (number) => chunk,   // or leave it to defaultHost()
//       readRequestBody: (number) => chunk,   // or leave it to worker()
//       writeResponseBody: (number, chunk2) => {},   // or leave it to worker()
//     },
//   });
//   await lisp.handleRequest(text);
//
// A host that suspends marks its own entries -- suspending(async (...) => ...)
// -- and every entry point above then answers a promise: the marked imports are
// wrapped in WebAssembly.Suspending and each entry point that can reach one is
// entered through WebAssembly.promising. This module was compiled --reentrant:
// it owns its per-call state, so calls are NOT serialised -- overlap them
// freely (what overlaps is the parked time; one stack still runs at a time).
// A read import's remainder is keyed by its arguments only, so two overlapped
// calls pulling one source through IDENTICAL arguments are the host's own
// hazard to serialise.
//
// This module's boundary is the reactor envelope, so the Request/Response half
// is derivable too and `worker` below is it:
//
//   import module from "./worker.wasm";
//   import { worker } from "./worker.js";
//
//   export default worker(module);
//
// Regenerate it, never edit it: --emit-js-glue on the compile that wrote the
// .wasm beside it.

const encoder = new TextEncoder();
// ignoreBOM, because these octets are a VALUE and not a document: a
// leading U+FEFF is a character the other side chose, and the default
// decoder deletes it -- silently shortening a BOM-prefixed request body
// by one character while the content-length beside it still counts three.
const decoder = new TextDecoder("utf-8", { ignoreBOM: true });

const SUSPENDING = Symbol.for("rontolisp.suspending");

/**
 * Marks a host function as one that answers a promise, so the wasm stack parks
 * until it settles (JSPI). The wrapper is not free -- an import answering
 * SYNCHRONOUSLY through one still returns to the event loop -- so mark only the
 * entries this host really implements asynchronously.
 *
 * @param {Function} fn the host function
 * @returns {object} the marked entry, to be passed as the import
 */
export function suspending(fn) {
  return { [SUSPENDING]: fn };
}

/**
 * Instantiates the module against this host and returns its callable surface.
 *
 * @param {WebAssembly.Module} module the compiled module
 * @param {object} host one function per import, keyed by module and field
 * @returns {object} `exports`, plus one entry point per rontolisp:wasm-export
 */
export function instantiate(module, host = {}) {
  let exports;

  // Every view is built where it is used, never held: growing the module's
  // memory DETACHES the buffer behind every view taken before the growth, and a
  // suspending host resumes after growths it never saw.
  const readString = (ptr, len) =>
    decoder.decode(new Uint8Array(exports.memory.buffer, ptr, len));

  // Octets, COPIED: the module pops the staging behind the pointer the moment
  // the call returns, so a chunk not taken by then is one the host never gets.
  const readBytes = (ptr, len) =>
    new Uint8Array(exports.memory.buffer.slice(ptr, ptr + len));

  // Bytes the HOST hands over live in the module's own bump allocator, and
  // cross as the (ptr, len) pair every memory-typed value is.
  const write = (octets) => {
    const ptr = exports.__ronto_alloc(octets.length);
    new Uint8Array(exports.memory.buffer, ptr, octets.length).set(octets);
    return [ptr, octets.length];
  };
  const writeString = (value) => write(encoder.encode(String(value)));
  // An import's text answer lives in a park block until the MODULE has copied
  // it out -- which it frees itself with __ronto_park_free.
  const writeParkString = (value) => {
    const octets = encoder.encode(String(value));
    const ptr = exports.__ronto_park_alloc(octets.length);
    new Uint8Array(exports.memory.buffer, ptr, octets.length).set(octets);
    return [ptr, octets.length];
  };
  const octets = (chunk) =>
    typeof chunk === "string" ? encoder.encode(chunk) : chunk;

  // A host answers a value, or -- from an entry it marked suspending -- a promise
  // of one. Both shapes ride one expression, which is what lets this file drive a
  // synchronous host and a JSPI host without being written twice.
  const marked = new Set();
  const unmarked = (what) =>
    what +
    " answered a promise; wrap it in suspending() so the wasm stack parks" +
    " until it settles";
  const settle = (what, value, next) => {
    if (typeof value?.then === "function") {
      if (!marked.has(what)) {
        // Reported before it is thrown: this throw crosses back into wasm,
        // where a catch_all landing pad turns it into whatever the module
        // makes of a failed import.
        console.error(unmarked(what));
        throw new TypeError(unmarked(what));
      }
      return value.then(next);
    }
    return next(value);
  };

  // The entries the module really imports: --optimize shakes out an import the
  // program never calls, and a host should not have to know which survived.
  const linked = new Set(
    WebAssembly.Module.imports(module).map((i) => i.module + "." + i.name),
  );
  const bind = (moduleName, field, wrap) => {
    const key = moduleName + "." + field;
    const given = (host[moduleName] ?? {})[field];
    if (given == null) {
      if (!linked.has(key)) return undefined;
      throw new TypeError("host." + key + " is missing; this module imports it");
    }
    if (given[SUSPENDING] === undefined) {
      // An async function that was never marked is the one mistake worth
      // catching HERE, where the report is a plain stack and not whatever
      // the module makes of an import that threw.
      if (given.constructor?.name === "AsyncFunction") {
        throw new TypeError(unmarked("host." + key));
      }
      return wrap(key, given);
    }
    marked.add(key);
    return new WebAssembly.Suspending(wrap(key, given[SUSPENDING]));
  };

  // A :bytes RESULT is the read(2) shape: the MODULE owns the buffer and asks
  // for up to `cap` octets, so what a host answers is the next CHUNK and this
  // holds whatever did not fit. Calls OVERLAP (--reentrant), so the remainders
  // are KEYED by the arguments that asked for them -- per call/reply id on the
  // id-carrying body protocol -- and each overlapped pull keeps its own; two
  // overlapped calls pulling one source through IDENTICAL arguments are the
  // host's own hazard to serialise. A remainder is dropped with the end of its
  // stream, never at the next entry: another call may be mid-pull.
  const readers = new Map();
  const reader = (what, source) => {
    const rests = new Map();
    readers.set(what, () => rests.clear());
    const drain = (key, rest, ptr, cap) => {
      const n = Math.min(cap, rest.length);
      new Uint8Array(exports.memory.buffer, ptr, n).set(rest.subarray(0, n));
      const left = rest.subarray(n);
      if (left.length === 0) rests.delete(key);
      else rests.set(key, left);
      return n;
    };
    // A read that FAILS answers a NEGATIVE count. Throwing would trap the
    // instance; the count is an error channel the module turns into a Lisp
    // condition where the octets are consumed.
    const failed = (error) => {
      console.error(what + " failed:", error);
      return -1;
    };
    return (args, ptr, cap) => {
      const key = JSON.stringify(args);
      const rest = rests.get(key);
      if (rest !== undefined) return drain(key, rest, ptr, cap);
      try {
        const answer = settle(what, source(...args), (chunk) => {
          if (chunk == null) return 0;
          const value = octets(chunk);
          return value.length === 0 ? 0 : drain(key, value, ptr, cap);
        });
        return typeof answer?.then === "function"
          ? answer.then(undefined, failed)
          : answer;
      } catch (error) {
        return failed(error);
      }
    };
  };

  // What a read import left over, thrown away on demand -- with no argument,
  // every remainder of every import.
  const drop = (key) =>
    key === undefined ? readers.forEach((f) => f()) : readers.get(key)?.();

  const imports = {
    env: {
      // (:string) -> :string
      fetch: bind("env", "fetch", (what, call) => {
        return (p0, p0Len) =>
          settle(what, call(readString(p0, p0Len)), writeParkString);
      }),
      // (:s32) -> :bytes
      readResponseBody: bind("env", "readResponseBody", (what, call) => {
        const read = reader(what, call);
        return (p0, ptr, cap) => read([p0], ptr, cap);
      }),
      // (:s32) -> :bytes
      readRequestBody: bind("env", "readRequestBody", (what, call) => {
        const read = reader(what, call);
        return (p0, ptr, cap) => read([p0], ptr, cap);
      }),
      // (:s32, :bytes) -> :void
      writeResponseBody: bind("env", "writeResponseBody", (what, call) => {
        return (p0, p1, p1Len) =>
          settle(what, call(p0, readBytes(p1, p1Len)), () => undefined);
      }),
    },
  };
  const instance = new WebAssembly.Instance(module, imports);
  exports = instance.exports;
  // Entropy, BEFORE the top level runs: a --no-wasi module imports none, so its
  // `random` starts from a constant and every instance would draw one sequence.
  // Seeding here also covers the draws a library makes while it LOADS. A Worker
  // forbids this in global scope, so instantiate on the first request.
  exports.__ronto_seed_random(
    new BigUint64Array(crypto.getRandomValues(new Uint8Array(8)).buffer)[0],
  );
  // And a clock, nanoseconds since the Unix epoch, for the same reason and
  // before the same line: until one is set the clock built-ins signal rather
  // than report 1970.
  exports.__ronto_set_time(BigInt(Date.now()) * 1000000n);
  exports._initialize();

  // The entry points a call chain can reach a suspending import from -- the
  // list the build prints -- entered through WebAssembly.promising exactly when
  // the host marked one. An unmarked host never pays for the promise.
  const suspends = marked.size !== 0;
  // --reentrant: NO serialisation queue. The module owns its per-call state
  // (task-scoped dynamic bindings, park-block staging), so overlapped calls
  // into one instance are the point of the build.
  const entry$handleRequest = suspends
    ? WebAssembly.promising(exports["handle-request"])
    : exports["handle-request"];

  // One call into the module (--reentrant, so calls may OVERLAP). The
  // argument staging is popped SYNCHRONOUSLY the moment the entry call
  // starts -- the wrapper boxes its parameters before its first suspension,
  // and by decode time another overlapped call may hold staging of its own
  // above the mark (the reset clamps to the module's park floor, so a park
  // block carved meanwhile survives the pop). Anything that must outlive
  // this synchronous window crosses in park blocks instead: `reserve`d
  // receive buffers, and the module's own :string/:s-expr results, which
  // `decode` frees with __ronto_park_free.
  const call = (run, entry, stage, decode) => {
    const work = () => {
      // The module's clock moves only when the host moves it, so move it per
      // call. Not a workaround for a frozen clock -- a Worker's own Date.now()
      // is frozen for the duration of a request as a timing-attack mitigation,
      // so a value that changes once per call is what the platform has.
      exports.__ronto_set_time(BigInt(Date.now()) * 1000000n);
      const mark = exports.__ronto_alloc_mark();
      const raw = entry(...stage());
      exports.__ronto_alloc_reset(mark);
      return typeof raw?.then === "function" ? raw.then(decode) : decode(raw);
    };
    return run(work);
  };

  /** `handle-request` -- (:string) -> :string */
  const make$handleRequest =
    (run) =>
    (p0) => {
      return call(
        run,
        entry$handleRequest,
        () => {
          const a0 = writeString(p0);
          return [a0[0], a0[1]];
        },
        ([ptr, len]) => {
          const value = readString(ptr, len);
          exports.__ronto_park_free(ptr);
          return value;
        },
      );
    };


  return {
    exports,
    handleRequest: make$handleRequest((work) => work()),
    drop,
  };
}

/**
 * The half of this boundary the module's own declarations FIX, ready to hand to
 * `instantiate` -- or to leave to `worker` below, which passes it for you. What
 * a host is still free to do is override it: whatever it supplies wins, entry by
 * entry.
 *
 * @returns {object} the import-object entries this file implements itself
 */
export function defaultHost() {
  // One reader per reply, keyed by the id the head carries back: overlapped
  // calls -- and a second fetch inside one call -- each drain their own. A
  // drained reader is dropped; one nobody drains stays until the platform
  // reclaims its stream.
  let replySerial = 0;
  const upstreams = new Map();
  return {
    env: {
      fetch: suspending(async (head) => {
        const request = JSON.parse(head);
        try {
          const response = await fetch(request.url, {
            method: request.method,
            headers: request.headers,
            body: request.body,
          });
          const id = ++replySerial;
          // The reader IS the body; the module pulls it BY THIS ID afterwards.
          if (response.body) upstreams.set(id, response.body.getReader());
          return JSON.stringify({
            status: response.status,
            headers: [...response.headers],
            "body-id": id,
          });
        } catch (error) {
          // The error arm becomes a Lisp condition at the fetch CALL; throwing
          // here would trap the instance instead, and take the request with it.
          return JSON.stringify({ error: String(error) });
        }
      }),
      readResponseBody: suspending(
        // The next chunk of the reply the id names, null at the end of it --
        // and for an id whose reply is already drained or was never opened.
        // Reading a ReadableStream is asynchronous, so this one really does
        // suspend; a read that THROWS becomes the negative count the module
        // signals at the drain, which the glue answers on our behalf.
        async (id) => {
          const upstream = upstreams.get(id);
          if (!upstream) return null;
          const { value, done } = await upstream.read();
          if (done) {
            upstreams.delete(id);
            return null;
          }
          return value;
        },
      ),
    },
  };
}

/**
 * This module as a fetch handler -- the whole Worker, with nothing left over:
 *
 *   import module from "./worker.wasm";
 *   import { worker } from "./worker.js";
 *
 *   export default worker(module);
 *
 * A Request becomes the envelope the module's entry point takes, the head it
 * answers becomes a Response, and the instance is created on the FIRST REQUEST
 * (a Worker forbids drawing entropy in global scope) and retired if a call ever
 * traps.
 *
 * @param {WebAssembly.Module} module the compiled module
 * @param {object} [options] `host` -- import entries, laid over defaultHost()'s
 *   one at a time; `remoteAddr` -- (request, env, ctx) => the client
 *   address, since which header carries it is the platform's business and not
 *   this file's (`(r) => r.headers.get("cf-connecting-ip")` on Cloudflare)
 * @returns {object} `{ fetch(request, env, ctx) }`
 */
export function worker(module, options = {}) {
  let instance = null;
  // Set when a call TRAPPED: that instance skipped its arena reset and its Lisp
  // state may be half-written, so nothing else may run on it. A Lisp ERROR is not
  // this -- the transport answers 500 itself and the instance is fine.
  let poisoned = false;
  // The request bodies the module pulls and the response bodies coming back,
  // keyed by the call id worker() mints per request: overlapped calls each
  // pull their own and collect their own.
  let callSerial = 0;
  const requestBodies = new Map();
  const responseChunks = new Map();
  const collected = (id) => {
    const chunks = responseChunks.get(id) ?? [];
    const all = new Uint8Array(
      chunks.reduce((n, chunk) => n + chunk.length, 0),
    );
    let at = 0;
    for (const chunk of chunks) {
      all.set(chunk, at);
      at += chunk.length;
    }
    return all;
  };
  const base = defaultHost();
  base.env = {
    ...(base.env ?? {}),
    readRequestBody: (id) => {
      // Handed over ONCE per call: a chunk source that never answers null is
      // one the module pulls forever.
      const chunk = requestBodies.get(id) ?? null;
      if (chunk) requestBodies.set(id, null);
      return chunk;
    },
    writeResponseBody: (id, chunk) => responseChunks.get(id)?.push(chunk),
  };
  const given = options.host ?? {};
  const host = {};
  for (const key of new Set([...Object.keys(base), ...Object.keys(given)])) {
    host[key] = { ...(base[key] ?? {}), ...(given[key] ?? {}) };
  }
  const live = () => {
    if (poisoned) {
      instance = null;
      poisoned = false;
    }
    return (instance ??= instantiate(module, host));
  };

  // The request head. `target` stays RAW -- path and query still joined and
  // still percent-encoded -- because the shared normalizer on the other side
  // owns that split, and a pre-split path leaves the query string nil.
  const envelope = (request, octets, remoteAddr, callId) => {
    const url = new URL(request.url);
    const headers = Object.fromEntries(request.headers);
    // A body with no content-length is a body the request parser does not read,
    // and a chunked request carries none -- so set it from the octets we have.
    if (octets?.length) headers["content-length"] = String(octets.length);
    const head = {
      method: request.method,
      target: url.pathname + url.search,
      headers,
      scheme: url.protocol.replace(":", ""),
      "call-id": callId,
    };
    if (remoteAddr != null) head["remote-addr"] = remoteAddr;
    return JSON.stringify(head);
  };

  return {
    // EVERYTHING is inside the try, not just the module call: reading an
    // aborted upload rejects, and `new Response` throws on a status or a
    // header an application is free to produce (0, 999, a newline in a
    // value). Outside it those escape as an unhandled rejection, which the
    // platform answers with its own error page and nothing in the log.
    async fetch(request, env, ctx) {
      let entered = false;
      let callId = 0;
      try {
        const remoteAddr = await options.remoteAddr?.(request, env, ctx);
        const octets = request.body
          ? new Uint8Array(await request.arrayBuffer())
          : null;
        callId = ++callSerial;
        const input = envelope(request, octets, remoteAddr, callId);
        requestBodies.set(callId, octets);
        responseChunks.set(callId, []);
        entered = true;
        const head = JSON.parse(await live().handleRequest(input));
        // Headers as an ARRAY of pairs, which keeps two Set-Cookie two.
        // An EMPTY body becomes null whichever shape it arrived in: 204/205/304
        // may only be constructed with a null body, and "" and a zero-length
        // Uint8Array are the same response as none.
        const body = head.body ?? collected(callId);
        return new Response(body?.length ? body : null, {
          status: head.status ?? 200,
          headers: head.headers ?? [],
        });
      } catch (error) {
        console.error("handle-request failed:", error);
        // Only a call that ENTERED the module can have left it half-written.
        // A mapping, or a Response the platform refused, says nothing about
        // the instance, and discarding it would cost the next request a
        // reinstantiation for someone else's bad header.
        if (entered) poisoned = true;
        return new Response("internal error\n", { status: 500 });
      }
      finally {
        // The call's body state goes with the call, on every path -- the
        // Response above reads the chunks before this runs.
        requestBodies.delete(callId);
        responseChunks.delete(callId);
      }
    },
  };
}
