(let ((s (objc:send "NSString" "stringWithUTF8String:" "hello objc")))
  (print s)
  (print (objc:send s "length"))
  (print (objc:send s "UTF8String"))
  (print (objc:send s "uppercaseString"))
  (print (objc:send (objc:send s "uppercaseString") "UTF8String")))
(print (objc:objectp (objc:class "NSObject")))
(print (handler-case (objc:send "NSObject" "fooBar") (error (e) (format nil "~a" e))))
(print (handler-case (objc:class "NoSuchThing") (error (e) (format nil "~a" e))))
(let ((a (objc:send "NSArray" "arrayWithObjects:" (objc:string "a") (objc:string "b") (objc:string "c"))))
  (print (objc:send a "count"))
  (print (objc:send (objc:send a "componentsJoinedByString:" "-") "UTF8String")))
(print (objc:send (objc:send "NSValue" "valueWithRect:" '(1.0 2.0 3.0 4.0)) "rectValue"))
(print (objc:bytes (objc:data "hey")))
(let* ((cls (objc:define-class "NativeE2eTarget" "NSObject"
             (list (list "ping:" (lambda (self x) (format t "ping ~a~%" (objc:send x "UTF8String")) nil)))))
       (obj (objc:send (objc:send cls "alloc") "init")))
  (objc:send obj "performSelector:withObject:" "ping:" (objc:string "from objc"))
  (print obj))
(print (handler-case (objc:send "NSString" "stringWithContentsOfFile:encoding:error:" "/nonexistent/x" 4 :error)
         (error (e) (princ-to-string e))))
(print (objc:send (objc:send "NSString" "stringWithContentsOfFile:encoding:error:" "/etc/hosts" 4 :error) "length"))
(let* ((cls (objc:define-class "NativeE2eBoom" "NSObject"
             (list (list "boom:" (lambda (self x) (error "boom ~a" (objc:send x "UTF8String"))))
                   (list "isEqual:" (lambda (self other) (objc:objectp other))))))
       (obj (objc:send (objc:send cls "alloc") "init")))
  (print (objc:send obj "performSelector:withObject:" "boom:" (objc:string "inside")))
  (print (objc:send obj "isEqual:" obj))
  (print (objc:send obj "isEqual:" nil))
  (print (handler-case (objc:define-class "NativeE2eBad" "NSObject" (list (list "description" (lambda (self) nil))))
           (error (e) (princ-to-string e)))))
(print (objc:on-main (lambda () (+ 1 2))))
(print (objc:bytes (objc:data (make-array 3 :element-type '(unsigned-byte 8) :initial-contents '(1 2 255)))))
(print (objc:send (objc:send "NSNumber" "numberWithDouble:" 2.5) "doubleValue"))
(print (objc:send (objc:send "NSNumber" "numberWithInt:" -7) "intValue"))
(print (objc:send (objc:send "NSNumber" "numberWithBool:" t) "boolValue"))
(print (objc:send (objc:send "NSNumber" "numberWithUnsignedLongLong:" 12345678901234) "unsignedLongLongValue"))
(print (objc:send (objc:send "NSValue" "valueWithPoint:" '(3.5 -1.0)) "pointValue"))
(print (objc:send (objc:send "NSValue" "valueWithRange:" '(5 10)) "rangeValue"))
(print (objc:send (objc:string "abc") "respondsToSelector:" "length"))
(print (objc:send (objc:string "abc") "characterAtIndex:" 1))
(print (handler-case (objc:send (objc:string "abc") "characterAtIndex:") (error (e) (princ-to-string e))))
(print (handler-case (objc:send (objc:string "abc") "characterAtIndex:" "x") (error (e) (princ-to-string e))))
(print (handler-case (objc:send (objc:string "abc") "length" 'foo) (error (e) (princ-to-string e))))
(print (handler-case (objc:send 42 "length") (error (e) (princ-to-string e))))
(print (objc:send nil "length"))
(print (objc:send (objc:send (objc:send "NSString" "stringWithFormat:" "%@-%ld-%.1f" (objc:string "x") 42 1.5) "description") "UTF8String"))
(print (objc:send (objc:send "NSValue" "valueWithSize:" '(640 480)) "sizeValue"))
(print (objc:send (objc:send "NSDecimalNumber" "decimalNumberWithString:" "1.25") "floatValue"))
(print (objc:send (objc:send "NSArray" "arrayWithObject:" (objc:string "only")) "firstObject"))
