(defun now () (java:static "java.lang.System" "nanoTime"))
(dotimes (r 3)
  (let ((t0 (now)) (acc 0))
    (dotimes (i 20000) (setq acc (+ acc (now))))
    (format t "~,2f us per now()~%" (/ (- (now) t0) 20000000.0))))
(let ((att (vec:zeros 256 :element-type 'single-float)) (scores (vec:ones 256 :element-type 'single-float)) (pos 110))
  (dotimes (r 3)
    (let ((t0 (now)))
      (dotimes (k 1000)
        (let ((top -1e30) (z 0.0) (inv 0.1443))
          (dotimes (u (+ pos 1))
            (let ((sc (* (aref scores u) inv)))
              (setf (aref att u) sc)
              (when (> sc top) (setq top sc))))
          (dotimes (u (+ pos 1))
            (let ((e (exp (- (aref att u) top))))
              (setf (aref att u) e)
              (setq z (+ z e))))
          (dotimes (u (+ pos 1)) (setf (aref att u) (/ (aref att u) z)))))
      (format t "softmax(111): ~,2f us per call~%" (/ (- (now) t0) 1000000.0)))))
