(define true #t)
(define false #f)
(define nil '())
(define the-empty-stream '())
(define (stream-null? s) (null? s))
(define (empty-stream? s) (null? s))
(define (stream-pair? s) (pair? s))
(define (shim-memo-proc proc)
  (let ((already-run? #f) (result #f))
    (lambda ()
      (if (not already-run?)
          (begin (set! result (proc)) (set! already-run? #t) result)
          result))))
(define (force p) (p))
(define (stream-car s) (car s))
(define (stream-cdr s) (force (cdr s)))
(define (stream-ref s n) (if (= n 0) (stream-car s) (stream-ref (stream-cdr s) (- n 1))))
(define (stream-head s n) (if (= n 0) '() (cons (stream-car s) (stream-head (stream-cdr s) (- n 1)))))
(define (stream-tail s n) (if (= n 0) s (stream-tail (stream-cdr s) (- n 1))))
(define (shim-any-null? ss) (cond ((null? ss) #f) ((null? (car ss)) #t) (else (shim-any-null? (cdr ss)))))
(define (stream-map proc . ss)
  (if (shim-any-null? ss) '()
      (cons (apply proc (map stream-car ss))
            (shim-memo-proc (lambda () (apply stream-map (cons proc (map stream-cdr ss))))))))
(define (stream-for-each proc s)
  (if (null? s) 'done (begin (proc (stream-car s)) (stream-for-each proc (stream-cdr s)))))
(define (stream-filter pred s)
  (cond ((null? s) '())
        ((pred (stream-car s)) (cons (stream-car s) (shim-memo-proc (lambda () (stream-filter pred (stream-cdr s))))))
        (else (stream-filter pred (stream-cdr s)))))
(define (stream-append s1 s2)
  (if (null? s1) s2 (cons (stream-car s1) (shim-memo-proc (lambda () (stream-append (stream-cdr s1) s2))))))
(define (caddr x) (car (cdr (cdr x))))
(define (cdddr x) (cdr (cdr (cdr x))))
(define (cadddr x) (car (cdr (cdr (cdr x)))))
(define (caadr x) (car (car (cdr x))))
(define (cdadr x) (cdr (car (cdr x))))
(define (cadar x) (car (cdr (car x))))
(define (cddar x) (cdr (cdr (car x))))
(define (caaar x) (car (car (car x))))
(define (shim-sqrt-iter g x n) (if (= n 0) g (shim-sqrt-iter (/ (+ g (/ x g)) 2.0) x (- n 1))))
(define (sqrt x) (if (= x 0) 0 (shim-sqrt-iter 1.0 x 60)))
(define (shim-series term x n acc) (if (= n 0) acc (shim-series term x (- n 1) (+ acc (term x n)))))
(define (exp x) (let loop ((n 1) (term 1.0) (acc 1.0)) (if (> n 60) acc (loop (+ n 1) (/ (* term x) n) (+ acc (/ (* term x) n))))))
(define (sin x) (let loop ((n 1) (term x) (acc x)) (if (> n 40) acc (let ((t (/ (* term (- 0 x) x) (* (* 2 n) (+ (* 2 n) 1))))) (loop (+ n 1) t (+ acc t))))))
(define (cos x) (sin (+ x 1.5707963267948966)))
(define (log x) (let loop ((y 0.0) (n 0)) (if (> n 60) y (loop (+ y (* 2.0 (/ (- x (exp y)) (+ x (exp y))))) (+ n 1)))))
(define (atan y . xs) (if (null? xs) (shim-atan1 y) (shim-atan2 y (car xs))))
(define (shim-atan1 z)
  (cond ((< z 0) (- 0 (shim-atan1 (- 0 z))))
        ((> z 1) (- 1.5707963267948966 (shim-atan1 (/ 1.0 z))))
        ((> z 0.5) (* 2 (shim-atan1 (/ z (+ 1 (sqrt (+ 1 (* z z))))))))
        (else (let loop ((n 0) (term z) (acc 0.0)) (if (> n 60) acc (loop (+ n 1) (* term (- 0 z) z) (+ acc (/ term (+ (* 2 n) 1)))))))))
(define (shim-atan2 y x)
  (cond ((> x 0) (shim-atan1 (/ y x)))
        ((and (< x 0) (>= y 0)) (+ (shim-atan1 (/ y x)) 3.141592653589793))
        ((< x 0) (- (shim-atan1 (/ y x)) 3.141592653589793))
        ((> y 0) 1.5707963267948966) ((< y 0) -1.5707963267948966) (else 0)))
(define shim-seed 12345)
(define (random n)
  (set! shim-seed (modulo (+ (* shim-seed 1103515245) 12345) 2147483648))
  (if (exact? n) (modulo (quotient shim-seed 7) n) (* n (/ shim-seed 2147483648.0))))
(define shim-clock 0)
(define (runtime) (set! shim-clock (+ shim-clock 1)) shim-clock)
(define (fold-right op init l) (if (null? l) init (op (car l) (fold-right op init (cdr l)))))
(define (fold-left op init l) (if (null? l) init (fold-left op (op init (car l)) (cdr l))))
(define (reduce op init l) (if (null? l) init (fold-left op (car l) (cdr l))))
(define (filter pred l) (cond ((null? l) '()) ((pred (car l)) (cons (car l) (filter pred (cdr l)))) (else (filter pred (cdr l)))))
(define (delete x l) (filter (lambda (y) (not (equal? x y))) l))
(define (last-pair l) (if (null? (cdr l)) l (last-pair (cdr l))))
(define (append! a b) (if (null? a) b (begin (set-cdr! (last-pair a) b) a)))
(define (1+ n) (+ n 1))
(define (-1+ n) (- n 1))
