#!/usr/bin/env bash
# Regenerates precomp/tests/fixtures/*.{wasm,out,status}: ci-slice.lisp is cut from
# ci-spec.yaml (the cases named below, verbatim, concatenated as CiSpecE2eTest does),
# every .lisp there is compiled by the rontolisp jar, and every .wasm is run under
# `wasmtime run` the way tests/stub.rs runs the stub: from <tmp>/cwd, beside <tmp>/up.txt,
# with the preopens the stub makes (the current directory under its absolute name, then
# `/`). What wasmtime prints is what the stub must print.
#
#   RONTOLISP_JAR   the -exec jar (default: ../target/rontolisp-*-exec.jar)
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
repo=$(dirname "$here")
fx=$here/precomp/tests/fixtures
jar=${RONTOLISP_JAR:-$(ls "$repo"/target/rontolisp-*-exec.jar | head -1)}

python3 - "$repo/src/test/resources/ci-spec.yaml" "$fx/ci-slice.lisp" <<'PY'
import sys, yaml
names = """arithmetic exact-integers-beyond-the-i64-range double-arithmetic-unboxed-and-fused
map-family-over-eleven-lists reduce-sort-search-order closure-mutation-capture-by-reference
condition-objects format-directives-conditional-iteration-jump hash-tables-cross-backend
defstruct-constructor-accessors-predicate-copier clos-defgeneric-defmethod-eql-dispatch""".split()
cases = {c["name"]: c for c in yaml.safe_load(open(sys.argv[1]))["cases"]}
with open(sys.argv[2], "w") as out:
    out.write(";; Generated by gen-fixtures.sh from src/test/resources/ci-spec.yaml -- do not edit.\n")
    for n in names:
        c = cases[n]
        assert "expectedByBackend" not in c, n
        out.write(c["source"] if c["source"].endswith("\n") else c["source"] + "\n")
PY

for src in "$fx"/*.lisp; do
  name=${src%.lisp}
  java -jar "$jar" "$src" -o "$name.wasm"
  work=$(mktemp -d)
  mkdir "$work/cwd"
  printf 'up\n' > "$work/up.txt"
  cwd=$(cd "$work/cwd" && pwd -P)
  set +e
  (cd "$cwd" && printf 'from stdin\n' | RLNATIVE_TEST=hello RLNATIVE_DIR=$cwd \
    wasmtime run --env RLNATIVE_TEST --env RLNATIVE_DIR --dir "$cwd::$cwd" --dir / "$name.wasm" alpha 'beta gamma' \
    > "$name.out" 2> /dev/null)
  echo $? > "$name.status"
  set -e
  rm -rf "$work"
  echo "$(basename "$name"): exit $(cat "$name.status"), $(wc -c < "$name.wasm") bytes of wasm"
done
