(println ())
(println (empty? []))
(defn greeting ([] (greeting "world")) ([username] (str "Hello, " username)))
(println (greeting))
(println (Thread/sleep 0))
(println (str (Class/forName "java.lang.String")))
(defprotocol Player (next-guess [player progress]))
(defrecord RandPlayer [])
(extend-protocol Player RandPlayer (next-guess [_ _] \a))
(println (next-guess (->RandPlayer) nil))
(println (satisfies? Player (->RandPlayer)))
(defrecord Note [pitch octave])
(extend-type Note Player (next-guess [this _] (:pitch this)))
(println (next-guess (->Note :C 4) nil))
(println (instance? String "x"))
(println (for [[idx val] (map-indexed vector [:a :b]) :when val] idx))
