(println "hello")
(declare m f)
(defn m [n] (if (zero? n) 0 (- n (f (m (dec n))))))
(defn f [n] (if (zero? n) 1 (- n (m (f (dec n))))))
(println (apply vector (map m (range 10))))
(declare my-odd? my-even?)
(defn my-odd? [n] (if (= n 0) false #(my-even? (dec n))))
(defn my-even? [n] (if (= n 0) true #(my-odd? (dec n))))
(println (trampoline my-even? 10000))
(defrecord Message [sender text])
(def messages (ref ()))
(defn add-message [msg] (dosync (alter messages (fn [m] (conj m msg)))))
(add-message (->Message "a" "hi"))
(println (:sender (first @messages)))
(defn coll-or-scalar [x & _] (if (coll? x) :collection :scalar))
(defmulti replace-symbol coll-or-scalar)
(defmethod replace-symbol :collection [coll oldsym newsym]
  (lazy-seq (when (seq coll)
              (cons (replace-symbol (first coll) oldsym newsym)
                    (replace-symbol (rest coll) oldsym newsym)))))
(defmethod replace-symbol :scalar [obj oldsym newsym]
  (if (= obj oldsym) newsym obj))
(println (replace-symbol '(a b (a c)) 'a 'z))
(defn index-filter [pred coll]
  (when pred (keep-indexed (fn [idx item] (when (pred item) idx)) coll)))
(defn index-of-any [pred coll]
  (first (index-filter pred coll)))
(println (index-of-any #{\b \y} "zzabyycdxx"))
(def ^:dynamic *d* 1)
(println (binding [*d* 2] *d*))
(.write *out* "wrote-this")
(println)
(ns g01 (:require [clojure.string :as str]))
(println (str/join "," ["a" "b"]))
(println (Math/sqrt 4.0))
(println (.. "abc" (substring 1) (toUpperCase)))
