;;; Interpreter driver: the host functions print what the node host prints.
(defun h1* (tag a) (princ "[") (princ tag) (princ " ") (princ a) (princ "]") (terpri))
(defun ha (a) (h1* "ha" a))
(defun hb (a) (h1* "hb" a))
(defun hc (a) (h1* "hc" a))
(defun hd (a) (h1* "hd" a))
(defun he (a) (h1* "he" a))
(defun hf (a) (h1* "hf" a))
(defun hg (a) (h1* "hg" a))
(defun hh (a) (h1* "hh" a))
(defun hi (a) (h1* "hi" a))
(defun h2 (a b) (princ "[h2 ") (princ a) (princ "|") (princ b) (princ "]") (terpri))
(defun h3 (a n b) (princ "[h3 ") (princ a) (princ "|") (princ n) (princ "|") (princ b) (princ "]") (terpri))
(load "body.lisp")
(run-all "runtime-string-arg")
