(defun h1 (a) (princ "[h1 ") (princ a) (princ "]") (terpri))
(defun c1 () (h1 "only-folded"))
(defun c2 () (h1 "both-ways") (print (length "both-ways")))
(defun c8 (s) (h1 s) (h1 "after"))
(defun run-all (s) (c1) (c2) (c8 s) (princ "done") (terpri))
(run-all "runtime-string-arg")
