;;; WASM driver: the host functions are imports, run-all is the export.
(rontolisp:wasm-import 'ha :from "env" :as "ha" :params '(:string) :returns nil)
(rontolisp:wasm-import 'hb :from "env" :as "hb" :params '(:string) :returns nil)
(rontolisp:wasm-import 'hc :from "env" :as "hc" :params '(:string) :returns nil)
(rontolisp:wasm-import 'hd :from "env" :as "hd" :params '(:string) :returns nil)
(rontolisp:wasm-import 'he :from "env" :as "he" :params '(:string) :returns nil)
(rontolisp:wasm-import 'hf :from "env" :as "hf" :params '(:string) :returns nil)
(rontolisp:wasm-import 'hg :from "env" :as "hg" :params '(:string) :returns nil)
(rontolisp:wasm-import 'hh :from "env" :as "hh" :params '(:string) :returns nil)
(rontolisp:wasm-import 'hi :from "env" :as "hi" :params '(:string) :returns nil)
(rontolisp:wasm-import 'h2 :from "env" :as "h2" :params '(:string :string) :returns nil)
(rontolisp:wasm-import 'h3 :from "env" :as "h3" :params '(:string :s32 :string) :returns nil)
(load "body.lisp")
(rontolisp:wasm-export 'run-all :as "RunAll" :params '(:string) :returns nil)
